# ====== Estructura de los datos ======

### Importacion de Librerias

In [1]:
import sys
!{sys.executable} -m pip install openpyxl
import pandas as pd

# Configuración para mostrar todas las columnas
pd.set_option('display.max_columns', None)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\yorie\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\yorie\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)

### Cargar los datasets desde data/raw

In [2]:
data2023 = pd.read_excel("../data/raw/2023_113_Reporte.xlsx")
data2024 = pd.read_excel("../data/raw/2024_113_Reporte.xlsx")
data2025 = pd.read_excel("../data/raw/2025_113_Reporte.xlsx")

### Agrupar datasets en un diccionario

In [3]:
datasets = {
    "2023": data2023,
    "2024": data2024,
    "2025": data2025
}

### Revisar dimensiones de los datasets

In [4]:
for year, df in datasets.items():
    print(f"\n===== DIMENSIONES DATASET {year} =====")
    print("Filas y columnas:", df.shape)

===== DIMENSIONES DATASET 2023 =====
Filas y columnas: (107, 126)

===== DIMENSIONES DATASET 2024 =====
Filas y columnas: (1441, 126)

===== DIMENSIONES DATASET 2025 =====
Filas y columnas: (1057, 126)

### Revisar tipos de datos

In [5]:
for year, df in datasets.items():
    print(f"\n===== TIPOS DE DATOS {year} =====")
    print(df.dtypes)

===== TIPOS DE DATOS 2023 =====
cod_eve         int64
fec_not        object
semana          int64
año             int64
cod_pre         int64
               ...
ndep_notif     object
nmun_notif     object
FechaHora      object
RegIniFec     float64
vacio           int64
Length: 126, dtype: object

===== TIPOS DE DATOS 2024 =====
cod_eve         int64
fec_not        object
semana          int64
año             int64
cod_pre         int64
               ...
ndep_notif     object
nmun_notif     object
FechaHora      object
RegIniFec     float64
vacio           int64
Length: 126, dtype: object

===== TIPOS DE DATOS 2025 =====
cod_eve        int64
fec_not       object
semana         int64
año            int64
cod_pre        int64
               ...
ndep_notif    object
nmun_notif    object
FechaHora     object
RegIniFec     object
vacio          int64
Length: 126, dtype: object

### Ver columnas de cada dataset

In [6]:
for year, df in datasets.items():
    print(f"\n===== COLUMNAS DATASET {year} =====")
    print(list(df.columns))

===== COLUMNAS DATASET 2023 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

===== COLUMNAS DATASET 2024 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

===== COLUMNAS DATASET 2025 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

### Revisar valores nulos

In [7]:
for year, df in datasets.items():
    print(f"\n===== NULOS DATASET {year} =====")
    print(df.isnull().sum().sort_values(ascending=False))

===== NULOS DATASET 2023 =====
otra_ident    107
otra_orien    107
sem_ges_      107
fm_grado      107
cbmte_        107
             ...
ndep_resi       0
ndep_notif      0
nmun_notif      0
FechaHora       0
vacio           0
Length: 126, dtype: int64

===== NULOS DATASET 2024 =====
otra_ident    1441
sem_ges_      1441
fm_unidad     1441
fm_grado      1441
cbmte_        1441
              ...
ndep_resi        0
ndep_notif       0
nmun_notif       0
FechaHora        0
vacio            0
Length: 126, dtype: int64

===== NULOS DATASET 2025 =====
otra_ident    1057
otra_orien    1057
sem_ges_      1057
fm_grado      1057
cbmte_        1057
              ...
ndep_resi        0
ndep_notif       0
nmun_notif       0
FechaHora        0
vacio            0
Length: 126, dtype: int64

### Ver solo columnas con nulos

In [8]:
for year, df in datasets.items():
    print(f"\n===== COLUMNAS CON NULOS {year} =====")
    
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0].sort_values(ascending=False)
    
    print(nulls)

===== COLUMNAS CON NULOS 2023 =====
sem_ges_                         107
otra_orien                       107
otra_ident                       107
estrato_datos_complementarios    107
RegIniFec                        107
fm_fuerza                        107
cer_def_                         107
fm_unidad                        107
fm_grado                         107
cbmte_                           107
iden_gener                       106
orient_sex                       106
cen_pobla_                       105
uni_modif                        102
nuni_modif                       102
bar_ver_                         101
localidad_                        94
lat_dir                           87
long_dir                          87
seg_nom_ma                        63
peso_nac                          54
diag_medic                        44
tipo_manej                        40
edad_ges                          33
seg_ape_ma                        32
seg_nom_                          30
vereda_                           21
nom_grupo_                        10
seg_ape_                           8
res_pr_ape                         8
telefono_                          5
gp_mad_com                         3
gp_gestan                          3
estrato_                           3
niv_educat                         2
dtype: int64

===== COLUMNAS CON NULOS 2024 =====
otra_ident         1441
fm_unidad          1441
fm_fuerza          1441
cbmte_             1441
cer_def_           1441
                   ...
zscore_te             1
ruta_atenc            1
palidez               1
cambios_cabello       1
hiperpigm             1
Length: 62, dtype: int64

===== COLUMNAS CON NULOS 2025 =====
otra_orien                       1057
otra_ident                       1057
fm_fuerza                        1057
cer_def_                         1057
cbmte_                           1057
sem_ges_                         1057
fm_grado                         1057
fm_unidad                        1057
estrato_datos_complementarios    1057
lat_dir                          1028
long_dir                         1028
cen_pobla_                       1006
localidad_                        905
bar_ver_                          869
seg_nom_ma                        641
peso_nac                          534
edad_ges                          328
orient_sex                        326
seg_ape_ma                        290
seg_nom_                          283
vereda_                           241
iden_gener                        227
telefono_                         225
res_pr_ape                        123
nom_grupo_                         97
tipo_manej                         64
diag_medic                         62
nuni_modif                         59
seg_ape_                           58
uni_modif                          28
estrato_                           16
niv_educat                         15
gp_gestan                          15
gp_mad_com                         15
gp_psiquia                          2
gp_migrant                          2
gp_indigen                          2
gp_pobicbf                          2
gp_discapa                          2
gp_desmovi                          2
gp_vic_vio                          2
gp_desplaz                          2
gp_carcela                          2
clas_peso                           2
clas_talla                          2
RegIniFec                           1
dtype: int64

### Porcentaje de datos faltantes

In [9]:
for year, df in datasets.items():
    print(f"\n===== PORCENTAJE DE NULOS {year} =====")
    
    percent = (df.isnull().sum() / len(df)) * 100
    print(percent.sort_values(ascending=False))

===== PORCENTAJE DE NULOS 2023 =====
otra_ident    100.0
otra_orien    100.0
sem_ges_      100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

===== PORCENTAJE DE NULOS 2024 =====
otra_ident    100.0
sem_ges_      100.0
fm_unidad     100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

===== PORCENTAJE DE NULOS 2025 =====
otra_ident    100.0
otra_orien    100.0
sem_ges_      100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

### Revisar duplicados

In [10]:
for year, df in datasets.items():
    print(f"\n===== DUPLICADOS DATASET {year} =====")
    print("Registros duplicados:", df.duplicated().sum())

===== DUPLICADOS DATASET 2023 =====
Registros duplicados: 0

===== DUPLICADOS DATASET 2024 =====
Registros duplicados: 0

===== DUPLICADOS DATASET 2025 =====
Registros duplicados: 0

### Ver primeras filas

In [11]:
for year, df in datasets.items():
    print(f"\n===== PRIMERAS FILAS DATASET {year} =====")
    display(df.head())

===== PRIMERAS FILAS DATASET 2023 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,10/01/2023,2,2023,4484700677,2,ELIENDER,SEGUNDO,IPUANA,GONZALEZ,RC,1124557354,6,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA TOSPA,NaN,RANCHERIA TOSPA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,10/01/2023,- -,4,2,- -,1,- -,7,3216532684,29/06/2022,NaN,NaN,NaN,NaN,- -,JOSE JAIME ALVAREZ,3005323756,20/02/2024,9001913221,NaN,NaN,NaN,Captura 1.6.31,MAGALIS,NaN,GONZALEZ,IPUANA,CC,27033702,5.0,1,2620.0,47,38.0,10,4,1,1,1,5,60,"11,5",1.0,"13,89","-2,2374",2,"-3,562",1,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,OUTTAJIAPULEE IPSI,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,20/02/2024,NaN,0
1,113,09/05/2023,19,2023,4400100441,1,ILDER,NaN,ARPUSIANA,PUSHAINA,RC,1225074831,1,1,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,1,3,NaN,NaN,COMUNIDAD MAZOYA,NaN,VIA SANTA MARTA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,NaN,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,1,09/05/2023,06/05/2023,4,1,09/05/2023,1,- -,7,3003713246,26/01/2022,NaN,NaN,NaN,NaN,- -,MARIA PAULA TORRES OLMOS,7282809,20/02/2024,825003806,NaN,NaN,NaN,Captura 1.6.31,DORIS,NaN,PUSHAINA,NaN,CC,40933715,5.0,2,2210.0,43,NaN,6,12,1,1,2,"4,6",56,"10,3",3.0,"14,7","-0,586",4,"-9,1475",1,2,1,1,1,1,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD DE CUIDADOS INTENSIVOS RENACER,COLOMBIA,GUAJIRA,RIOHACHA,COLOMBIA,GUAJIRA,RIOHACHA,GUAJIRA,RIOHACHA,20/02/2024,NaN,0
2,113,08/05/2023,19,2023,4484700836,1,DEINER,JOSE,EPIEYU,NaN,RC,1124557968,1,1,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA SARIJANOU,NaN,RANCHERIA WARIJANOU,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,08/05/2023,01/05/2023,4,1,08/05/2023,1,- -,7,3148079349,13/04/2022,NaN,NaN,NaN,NaN,- -,LUIS MIGUEL IGUARAN,3108313376,20/02/2024,900492815,NaN,NaN,NaN,Captura 1.6.31,MILEIDY,NaN,EPIAYU,NaN,CC,1151458545,1.0,2,NaN,0,38.0,6,6,1,1,1,"7,4","71,5","12,1",3.0,"14,5","-2,1066",2,"-1,788",2,2,1,2,2,1,2,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD MATERNO INFANTIL TALAPUIN SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,20/02/2024,NaN,0
3,113,04/10/2023,40,2023,2057000983,5,DWIA,RUKUNGUMU,MEJIA,CRESPO,RC,1063604976,10,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,SIMONORWA,NaN,SIMONORWA,NaN,NaN,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,04/10/2023,04/08/2023,4,2,- -,1,- -,7,SIN INFORMACIÓN,24/11/2022,NaN,NaN,NaN,NaN,- -,DANIELA BURGOS,3128439725,20/02/2024,9000736458,NaN,NaN,NaN,Captura 1.6.31,GUNEIWIA,NaN,CRESPO,TORRES,CC,1148197258,5.0,1,NaN,0,40.0,6,6,1,3,2,"7,3",72,13,1.0,"14,1","-2,4425",2,"-0,5607",3,2,1,2,1,1,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CENTRO DE SALUD PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,20/02/2024,NaN,0
4,113,11/05/2023,19,2023,2057000236,1,KARILIS,LICET,NIÑO,TORRES,RC,1063604045,1,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,"PALM,ARITO",NaN,PALMARITO,NaN,NaN,99999.07,S,EPSI01,6,NaN,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,11/05/2023,01/03/2023,4,1,11/05/2023,1,- -,7,SIN INFORMACIÓN,11/03/2022,NaN,NaN,NaN,NaN,- -,ANNY BAYONA,3165200035,22/02/2024,8240026728,NaN,NaN,NaN,Captura 1.6.31,JOHINER,DURAWINO,NIÑO,ARROYO,CC,113984904,1.0,1,NaN,0,NaN,6,6,2,1,2,"7,3","70,5",6,3.0,"14,7","-1,4033",3,"-2,1914",1,1,1,1,1,1,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,ESE HOSPITAL CAMILO VILLAZON PUMAREJO,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,22/02/2024,NaN,0

===== PRIMERAS FILAS DATASET 2024 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,19/01/2024,3,2024,2001301346,2,KELLY,NONE,FRANCO,PEREZ,RC,1300422455,1,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,13,1,NaN,NaN,NaN,9999999 SIN INFORMACION,ASENTAMIENTO NEIPO,0.0,0.0,9999.00,S,EPSI01,1,YUKPA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,13,17/01/2024,15/01/2024,4,1,17/01/2024,1,- -,0,SIN INFORMACION,22/12/2022,NaN,NaN,NaN,NaN,21/01/2024,MARIA DAVID,3003715918,19/01/2024,9003457651,NaN,NaN,NaN,SIVIGILA - 2018 -18.4.3$0$0.0,LIDIA,NONE,PEREZ,PEÑALOZA,CC,1133485557,5.0,1.0,2500.0,49.0,39.0,6.0,12.0,1.0,3.0,2.0,"6,5",69,12,NaN,"13,65","-2,3146",2.0,"-1,9476",2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CLINICA CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,AGUSTIN CODAZZI,21/01/2024,NaN,0
1,113,06/01/2024,1,2024,2000101794,1,RUMALDA,NaN,ARROYO,COTES,RC,1063604975,2,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,570,1,NaN,NaN,NaN,CASA INDIGENA,CASA INIDIGENA,0.0,0.0,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,06/01/2024,04/01/2023,4,1,06/01/2024,1,- -,0,3113527221,10/01/2022,NaN,NaN,NaN,NaN,16/01/2024,GUILLERMO MARTINEZ,0,13/01/2024,9006010527,NaN,NaN,NaN,SIVIGILA - 2018 -18.6.5$0$0.0,MAMA DE RUMALDA,NaN,COSTES,NaN,CC,1148140406,5.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,"7,8",70,13,3.0,"15,92","-0,506",4.0,"-4,8903",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD PEDIATRICA SIMON BOLIVAR,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,VALLEDUPAR,16/01/2024,NaN,0
2,113,15/03/2024,11,2024,2000100012,1,YAIR,HERNANDO,MONTES,GARCIA,RC,1300421976,10,2,170,COLOMBIA,M,1.0,NaN,1.0,NaN,170,20,13,3,NaN,NaN,EL LIMON,NaN,EL LIMON,NaN,NaN,99999.07,S,EPSI01,1,YUKPA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,13,15/03/2024,02/03/2024,4,1,16/03/2024,1,- -,0,NaN,27/04/2023,NaN,NaN,NaN,NaN,- -,EDER GAMEZMENDOZA SISSIV[C00],5804440,16/03/2024,8240023621,NaN,NaN,NaN,Captura 1.6.31,ESMERALDA,NaN,GARCIA,PEÑA,CC,1010092024,5.0,0.0,NaN,0.0,NaN,10.0,6.0,2.0,3.0,2.0,"6,5",68,11,1.0,"14,1","-2,5691",2.0,"-2,3113",1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,VALLEDUPAR,16/03/2024,NaN,0
3,113,15/01/2024,3,2024,4484700332,1,GERARDO,JOSE,URIANA,PUSHAINA,RC,1124558195,1,1,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,COMUNIDAD PERROUTALIAMANA,NaN,COMUNIDAD PERROUTALIMANA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,1,2,2,2,2.0,NaN,2,2,2.0,2,2,2,2,1,170,44,847,15/01/2024,- -,4,2,- -,1,- -,0,SIN INFORMACIÓN,04/09/2022,NaN,NaN,NaN,NaN,- -,ANGIE MONTALVO SISSIV[C00],3013950445,18/01/2024,8000617659,NaN,NaN,NaN,Captura 1.6.31,PIDELINA,NaN,URIANA,PUSHAINA,CC,1147940070,1.0,1.0,2745.0,49.0,38.0,6.0,6.0,1.0,1.0,1.0,"7,4","72,5",12,1.0,"14,1","-2,4222",2.0,"-2,9838",1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,HOSPITAL NUESTRA SEÑORA DEL PERPETUO SOCORRO,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,18/01/2024,NaN,0
4,113,04/01/2024,1,2024,2000100012,1,LUZ,ADIELA,WEPA,ESTRADA,RC,1067737278,1,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,13,3,NaN,NaN,NANAESCHPO,NaN,NANAESCHPO,NaN,NaN,99999.07,S,EPSI01,1,YUKPA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,13,03/01/2024,25/12/2023,4,1,04/01/2024,1,- -,0,31455274603,23/12/2022,NaN,NaN,NaN,NaN,- -,CARLOS MARIO RODRIGUEZ,5804440,04/01/2024,8240023621,NaN,NaN,NaN,Captura 1.6.31,VANESA,NaN,ESTRADA,ESTRADA,AS,1508627265733,5.0,2.0,NaN,0.0,NaN,12.0,6.0,2.0,3.0,2.0,"8,1",72,0,3.0,"15,6","-0,6277",4.0,"-0,7825",3.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,E43X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,VALLEDUPAR,04/01/2024,NaN,0

===== PRIMERAS FILAS DATASET 2025 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,11/01/2025,2,2025,2000100012,1,SHAIRA,ANGELA,HERRERA,ESTRADA,RC,1133485771,1,1,170,COLOMBIA,F,2.0,NaN,1.0,NaN,170,20,13,3,NaN,NaN,NANESCHPO,NaN,NANESCHPO,NaN,NaN,99999.07,S,EPSI01,1,YUKPA,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,20,13,11/01/2025,10/01/2025,4,1,12/01/2025,1,- -,0,SIN INFORMACIÓN,27/11/2023,NaN,NaN,200010001201,DUSAKAWI IPS,- -,MARIA LAURA ARIAS,5804440,14/01/2025,8240023621,NaN,NaN,NaN,Captura 2.0.5,MERLY,NaN,ESTRADA,ESTRADA,TI,1214468379,5.0,0,2500.0,0,39.0,13,6,2,3,2,"6,8",70,11,3.0,"13,9","-2,0869",2.0,"-1,9842",2.0,2,1,1,1,1,2,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,VALLEDUPAR,14/01/2025,14/01/2025,0
1,113,09/01/2025,2,2025,4484700351,2,SHAROL,PATRICIA,FERNANDEZ,NaN,RC,1131082275,7,2,170,COLOMBIA,F,2.0,NaN,1.0,NaN,170,44,847,3,NaN,NaN,SUCARAMANA,NaN,CORREGIMIENTO IRRAIPA RANCHERIA SUCARAMANA CER...,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,09/01/2025,04/01/2025,4,2,- -,1,- -,7,3137472383,28/05/2024,NaN,NaN,448470035102,IPSI SUPULA WAYUU URIBIA,- -,DANIELA HUMANEZ,3017817650,11/01/2025,8250031495,NaN,NaN,NaN,Captura 2.0.5,DAILIS,NaN,JUSAYU,NaN,CC,1147949535,2.0,1,2800.0,40,38.0,7,7,1,1,1,"5,2","61,5","11,5",1.0,"13,7","-2,0879",2.0,"-2,4995",1.0,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,IPSI SUPULA WAYUU URIBIA,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,11/01/2025,09/01/2025,0
2,113,10/01/2025,2,2025,4484700332,1,AMAURY,DE JESUS,FINCE,EPIEYU,RC,1124563067,1,1,170,COLOMBIA,M,1.0,NaN,1.0,NaN,170,44,847,3,NaN,NaN,COMUNIDAD WAJALECHON,NaN,COMUNIDAD WAJALECHON VIA POPORTIN,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,10/01/2025,- -,4,2,- -,1,- -,0,SIN INFORMACIÓN,19/07/2023,NaN,NaN,448470033201,HOSPITAL NUESTRA SEÑORA DEL PERPETUO SOCORRO,- -,KASANDRA SOLANO,3044704970,14/01/2025,8000617659,NaN,NaN,NaN,Captura 2.0.5,SANDRA,YULIANA,EPIEYU,NaN,CC,1124358430,1.0,1,2750.0,50,39.0,14,6,1,1,2,"7,85",75,"12,5",1.0,14,"-2,3833",2.0,"-2,3664",1.0,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,HOSPITAL NUESTRA SEÑORA DEL PERPETUO SOCORRO,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,14/01/2025,14/01/2025,0
3,113,05/01/2025,2,2025,4484701173,1,MILEIXY,MILENA,URIANA,PUSHAINA,RC,114037675,2,1,170,COLOMBIA,F,2.0,NaN,NaN,NaN,170,44,847,3,NaN,NaN,ICHICHO,NaN,VEREDA ICHICHO KM 134 VIA PUERTO BOLIVAR,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,05/01/2025,01/01/2025,4,2,- -,1,- -,D,SIN INFORMACIÓN,01/08/2022,NaN,NaN,448470117301,CENTRO MEDICO COLSANITAS PREMIUM PUERTO BOLIVAR,- -,HUMBERTO GONZALEZ PEÑA,3126124609,27/01/2025,901041691,NaN,NaN,NaN,Captura 2.0.4,MARIANITA,NaN,PUSHAINA,IPUANA,CC,56100875,5.0,1,NaN,0,NaN,12,6,2,3,2,"8,3",79,13,3.0,"13,3","-2,1944",2.0,"-3,1311",1.0,2,1,1,2,2,2,2,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CENTRO MEDICO COLSANITAS PREMIUM PUERTO BOLIVAR,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,27/01/2025,06/01/2025,0
4,113,10/01/2025,2,2025,4484700351,2,FRANYIMAR,ELENA,CASTILLO,JUSAYU,RC,1245829963,1,1,170,COLOMBIA,F,2.0,NaN,1.0,NaN,170,44,847,1,URIBIA,NaN,NaN,AIPIAMANA,BARRIO AIPIAMANA POR LA TIENDA ANTONELLA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,10/01/2025,02/01/2025,4,2,- -,1,- -,0,3135168265,31/07/2023,NaN,NaN,448470035102,IPSI SUPULA WAYUU URIBIA,- -,MARIA KARINA ESCORCIA,3014589333,07/02/2025,8250031495,NaN,NaN,NaN,Captura 2.0.8,MARIA,ZUNILDA,JUSAYU,PUSHAINA,CC,1006917401,1.0,1,3000.0,49,39.0,12,8,1,1,1,"7,4",74,"13,5",1.0,"13,5","-2,201",2.0,"-1,9905",2.0,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,IPSI SUPULA WAYUU URIBIA,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,07/02/2025,07/02/2025,0

### Comparar si las columnas son iguales entre datasets

In [12]:
print("¿Columnas iguales entre 2023 y 2024?")
print(set(data2023.columns) == set(data2024.columns))

print("\n¿Columnas iguales entre 2023 y 2025?")
print(set(data2023.columns) == set(data2025.columns))

¿Columnas iguales entre 2023 y 2024?
True

¿Columnas iguales entre 2023 y 2025?
True

# ====== Variable Objetivo ======

In [13]:
for col in data2023.columns:
    print(col, "-", data2023[col].nunique())

cod_eve - 1
fec_not - 82
semana - 42
año - 1
cod_pre - 41
cod_sub - 11
pri_nom_ - 89
seg_nom_ - 53
pri_ape_ - 57
seg_ape_ - 46
tip_ide_ - 3
num_ide_ - 96
edad_ - 11
uni_med_ - 3
nacionali_ - 1
nombre_nacionalidad - 1
sexo_ - 2
iden_gener - 1
otra_ident - 0
orient_sex - 1
otra_orien - 0
cod_pais_o - 1
cod_dpto_o - 3
cod_mun_o - 12
area_ - 3
localidad_ - 8
cen_pobla_ - 2
vereda_ - 69
bar_ver_ - 6
dir_res_ - 93
lat_dir - 2
long_dir - 2
ocupacion_ - 2
tip_ss_ - 1
cod_ase_ - 1
per_etn_ - 2
nom_grupo_ - 6
estrato_ - 2
gp_discapa - 1
gp_desplaz - 1
gp_migrant - 1
gp_carcela - 1
gp_gestan - 1
sem_ges_ - 0
gp_indigen - 1
gp_pobicbf - 2
gp_mad_com - 1
gp_desmovi - 1
gp_psiquia - 1
gp_vic_vio - 1
gp_otros - 2
fuente_ - 4
cod_pais_r - 1
cod_dpto_r - 4
cod_mun_r - 13
fec_con_ - 83
ini_sin_ - 78
tip_cas_ - 1
pac_hos_ - 2
fec_hos_ - 40
con_fin_ - 1
fec_def_ - 1
ajuste_ - 4
telefono_ - 56
fecha_nto_ - 91
cer_def_ - 0
cbmte_ - 0
uni_modif - 4
nuni_modif - 4
fec_arc_xl - 8
nom_dil_f_ - 81
tel_dil_f_ - 70
fec_aju_ - 25
nit_upgd - 37
fm_fuerza - 0
fm_unidad - 0
fm_grado - 0
version - 8
pri_nom_ma - 92
seg_nom_ma - 34
pri_ape_ma - 56
seg_ape_ma - 44
tip_ide_ma - 5
num_ide_ma - 96
niv_educat - 4
menores - 7
peso_nac - 22
talla_nac - 12
edad_ges - 10
t_lechem - 18
e_complem - 12
crec_dllo - 2
esq_vac - 3
carne_vac - 2
peso_act - 60
talla_act - 53
per_braqui - 23
res_pr_ape - 3
imc - 62
zscore_pt - 98
clas_peso - 7
zscore_te - 99
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 5
estrato_datos_complementarios - 0
nom_eve - 1
nom_upgd - 41
npais_proce - 1
ndep_proce - 3
nmun_proce - 14
npais_resi - 1
ndep_resi - 4
nmun_resi - 15
ndep_notif - 5
nmun_notif - 14
FechaHora - 25
RegIniFec - 0
vacio - 1

### filtramos columnas con pocos valores únicos, que suelen ser targets en clasificación.

In [14]:
for col in data2023.columns:
    unique_vals = data2023[col].nunique()
    
    if 2 <= unique_vals <= 10:
        print(col, "-", unique_vals)

tip_ide_ - 3
uni_med_ - 3
sexo_ - 2
cod_dpto_o - 3
area_ - 3
localidad_ - 8
cen_pobla_ - 2
bar_ver_ - 6
lat_dir - 2
long_dir - 2
ocupacion_ - 2
per_etn_ - 2
nom_grupo_ - 6
estrato_ - 2
gp_pobicbf - 2
gp_otros - 2
fuente_ - 4
cod_dpto_r - 4
pac_hos_ - 2
ajuste_ - 4
uni_modif - 4
nuni_modif - 4
fec_arc_xl - 8
version - 8
tip_ide_ma - 5
niv_educat - 4
menores - 7
edad_ges - 10
crec_dllo - 2
esq_vac - 3
carne_vac - 2
res_pr_ape - 3
clas_peso - 7
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 5
ndep_proce - 3
ndep_resi - 4
ndep_notif - 5

In [15]:
data2023["clas_peso"].value_counts()

clas_peso
2    66
1    14
3    11
4    10
5     3
7     2
6     1
Name: count, dtype: int64