# ====== Estructura de los datos ======

### Importacion de Librerias

In [1]:
import sys
!{sys.executable} -m pip install openpyxl gcsfs --quiet
import pandas as pd

# Configuración para mostrar todas las columnas
pd.set_option('display.max_columns', None)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
s3fs 2025.3.2 requires fsspec==2025.3.2.*, but you have fsspec 2026.3.0 which is incompatible.

### Cargar los datasets desde data/external y data/raw

In [2]:
bucket_url = "gs://data_desnutricion"
file_names = {
    "2020": "2020_113_Reporte.xlsx",
    "2021": "2021_113_Reporte.xlsx",
    "2022": "2022_113_Reporte.xlsx",
    "2023": "2023_113_Reporte.xlsx",
    "2024": "2024_113_Reporte.xlsx",
    "2025": "2025_113_Reporte.xlsx",
}

datasets = {}
for year, file_name in file_names.items():
    url = f"{bucket_url}/{file_name}"
    print(f"Cargando {year} desde {url}")
    datasets[year] = pd.read_excel(
        url,
        engine="openpyxl",
        storage_options={"token": "google_default"}
    )
    print(f"{year}: {datasets[year].shape[0]:,} filas x {datasets[year].shape[1]} columnas")

Cargando 2020 desde gs://data_desnutricion/2020_113_Reporte.xlsx
2020: 320 filas x 126 columnas
Cargando 2021 desde gs://data_desnutricion/2021_113_Reporte.xlsx
2021: 580 filas x 126 columnas
Cargando 2022 desde gs://data_desnutricion/2022_113_Reporte.xlsx
2022: 850 filas x 126 columnas
Cargando 2023 desde gs://data_desnutricion/2023_113_Reporte.xlsx
2023: 107 filas x 126 columnas
Cargando 2024 desde gs://data_desnutricion/2024_113_Reporte.xlsx
2024: 1,441 filas x 126 columnas
Cargando 2025 desde gs://data_desnutricion/2025_113_Reporte.xlsx
2025: 1,057 filas x 126 columnas

### Agrupar datasets en un diccionario

In [3]:
# El diccionario datasets ya fue creado directamente desde GCS.

### Revisar dimensiones de los datasets

In [4]:
for year, df in datasets.items():
    print(f"\n===== DIMENSIONES DATASET {year} =====")
    print("Filas y columnas:", df.shape)

===== DIMENSIONES DATASET 2020 =====
Filas y columnas: (320, 126)

===== DIMENSIONES DATASET 2021 =====
Filas y columnas: (580, 126)

===== DIMENSIONES DATASET 2022 =====
Filas y columnas: (850, 126)

===== DIMENSIONES DATASET 2023 =====
Filas y columnas: (107, 126)

===== DIMENSIONES DATASET 2024 =====
Filas y columnas: (1441, 126)

===== DIMENSIONES DATASET 2025 =====
Filas y columnas: (1057, 126)

### Revisar tipos de datos

In [5]:
for year, df in datasets.items():
    print(f"\n===== TIPOS DE DATOS {year} =====")
    print(df.dtypes)

===== TIPOS DE DATOS 2020 =====
cod_eve         int64
fec_not        object
semana          int64
año             int64
cod_pre         int64
               ...
ndep_notif     object
nmun_notif     object
FechaHora      object
RegIniFec     float64
vacio           int64
Length: 126, dtype: object

===== TIPOS DE DATOS 2021 =====
cod_eve         int64
fec_not        object
semana          int64
año             int64
cod_pre         int64
               ...
ndep_notif     object
nmun_notif     object
FechaHora      object
RegIniFec     float64
vacio           int64
Length: 126, dtype: object

===== TIPOS DE DATOS 2022 =====
cod_eve         int64
fec_not        object
semana          int64
año             int64
cod_pre         int64
               ...
ndep_notif     object
nmun_notif     object
FechaHora      object
RegIniFec     float64
vacio           int64
Length: 126, dtype: object

===== TIPOS DE DATOS 2023 =====
cod_eve         int64
fec_not        object
semana          int64
año             int64
cod_pre         int64
               ...
ndep_notif     object
nmun_notif     object
FechaHora      object
RegIniFec     float64
vacio           int64
Length: 126, dtype: object

===== TIPOS DE DATOS 2024 =====
cod_eve         int64
fec_not        object
semana          int64
año             int64
cod_pre         int64
               ...
ndep_notif     object
nmun_notif     object
FechaHora      object
RegIniFec     float64
vacio           int64
Length: 126, dtype: object

===== TIPOS DE DATOS 2025 =====
cod_eve        int64
fec_not       object
semana         int64
año            int64
cod_pre        int64
               ...
ndep_notif    object
nmun_notif    object
FechaHora     object
RegIniFec     object
vacio          int64
Length: 126, dtype: object

### Ver columnas de cada dataset

In [6]:
for year, df in datasets.items():
    print(f"\n===== COLUMNAS DATASET {year} =====")
    print(list(df.columns))

===== COLUMNAS DATASET 2020 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

===== COLUMNAS DATASET 2021 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

===== COLUMNAS DATASET 2022 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

===== COLUMNAS DATASET 2023 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

===== COLUMNAS DATASET 2024 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

===== COLUMNAS DATASET 2025 =====
['cod_eve', 'fec_not', 'semana', 'año', 'cod_pre', 'cod_sub', 'pri_nom_', 'seg_nom_', 'pri_ape_', 'seg_ape_', 'tip_ide_', 'num_ide_', 'edad_', 'uni_med_', 'nacionali_', 'nombre_nacionalidad', 'sexo_', 'iden_gener', 'otra_ident', 'orient_sex', 'otra_orien', 'cod_pais_o', 'cod_dpto_o', 'cod_mun_o', 'area_', 'localidad_', 'cen_pobla_', 'vereda_', 'bar_ver_', 'dir_res_', 'lat_dir', 'long_dir', 'ocupacion_', 'tip_ss_', 'cod_ase_', 'per_etn_', 'nom_grupo_', 'estrato_', 'gp_discapa', 'gp_desplaz', 'gp_migrant', 'gp_carcela', 'gp_gestan', 'sem_ges_', 'gp_indigen', 'gp_pobicbf', 'gp_mad_com', 'gp_desmovi', 'gp_psiquia', 'gp_vic_vio', 'gp_otros', 'fuente_', 'cod_pais_r', 'cod_dpto_r', 'cod_mun_r', 'fec_con_', 'ini_sin_', 'tip_cas_', 'pac_hos_', 'fec_hos_', 'con_fin_', 'fec_def_', 'ajuste_', 'telefono_', 'fecha_nto_', 'cer_def_', 'cbmte_', 'uni_modif', 'nuni_modif', 'fec_arc_xl', 'nom_dil_f_', 'tel_dil_f_', 'fec_aju_', 'nit_upgd', 'fm_fuerza', 'fm_unidad', 'fm_grado', 'version', 'pri_nom_ma', 'seg_nom_ma', 'pri_ape_ma', 'seg_ape_ma', 'tip_ide_ma', 'num_ide_ma', 'niv_educat', 'menores', 'peso_nac', 'talla_nac', 'edad_ges', 't_lechem', 'e_complem', 'crec_dllo', 'esq_vac', 'carne_vac', 'peso_act', 'talla_act', 'per_braqui', 'res_pr_ape', 'imc', 'zscore_pt', 'clas_peso', 'zscore_te', 'clas_talla', 'edema', 'delgadez', 'piel_rese', 'hiperpigm', 'cambios_cabello', 'palidez', 'ruta_atenc', 'tipo_manej', 'diag_medic', 'estrato_datos_complementarios', 'nom_eve', 'nom_upgd', 'npais_proce', 'ndep_proce', 'nmun_proce', 'npais_resi', 'ndep_resi', 'nmun_resi', 'ndep_notif', 'nmun_notif', 'FechaHora', 'RegIniFec', 'vacio']

### Revisar valores nulos

In [7]:
for year, df in datasets.items():
    print(f"\n===== NULOS DATASET {year} =====")
    print(df.isnull().sum().sort_values(ascending=False))

===== NULOS DATASET 2020 =====
otra_ident    320
otra_orien    320
sem_ges_      320
fm_grado      320
cbmte_        320
             ...
ndep_resi       0
ndep_notif      0
nmun_notif      0
FechaHora       0
vacio           0
Length: 126, dtype: int64

===== NULOS DATASET 2021 =====
otra_ident    580
otra_orien    580
sem_ges_      580
fm_grado      580
cbmte_        580
             ...
ndep_resi       0
ndep_notif      0
nmun_notif      0
FechaHora       0
vacio           0
Length: 126, dtype: int64

===== NULOS DATASET 2022 =====
otra_ident    850
otra_orien    850
sem_ges_      850
fm_grado      850
cbmte_        850
             ...
ndep_resi       0
ndep_notif      0
nmun_notif      0
FechaHora       0
vacio           0
Length: 126, dtype: int64

===== NULOS DATASET 2023 =====
otra_ident    107
otra_orien    107
sem_ges_      107
fm_grado      107
cbmte_        107
             ...
ndep_resi       0
ndep_notif      0
nmun_notif      0
FechaHora       0
vacio           0
Length: 126, dtype: int64

===== NULOS DATASET 2024 =====
otra_ident    1441
sem_ges_      1441
fm_unidad     1441
fm_grado      1441
cbmte_        1441
              ...
ndep_resi        0
ndep_notif       0
nmun_notif       0
FechaHora        0
vacio            0
Length: 126, dtype: int64

===== NULOS DATASET 2025 =====
otra_ident    1057
otra_orien    1057
sem_ges_      1057
fm_grado      1057
cbmte_        1057
              ...
ndep_resi        0
ndep_notif       0
nmun_notif       0
FechaHora        0
vacio            0
Length: 126, dtype: int64

### Ver solo columnas con nulos

In [8]:
for year, df in datasets.items():
    print(f"\n===== COLUMNAS CON NULOS {year} =====")
    
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0].sort_values(ascending=False)
    
    print(nulls)

===== COLUMNAS CON NULOS 2020 =====
sem_ges_                         320
otra_orien                       320
otra_ident                       320
fm_unidad                        320
estrato_datos_complementarios    320
RegIniFec                        320
fm_grado                         320
cer_def_                         320
fm_fuerza                        320
cbmte_                           320
cen_pobla_                       302
localidad_                       280
bar_ver_                         253
seg_nom_ma                       204
peso_nac                         184
orient_sex                       144
nuni_modif                       141
uni_modif                        132
iden_gener                       116
edad_ges                         108
seg_ape_ma                       104
seg_nom_                          96
diag_medic                        33
nom_grupo_                        27
tipo_manej                        18
seg_ape_                          12
gp_psiquia                        10
gp_desplaz                        10
niv_educat                        10
ajuste_                            7
gp_vic_vio                         7
gp_indigen                         6
estrato_                           6
cod_dpto_r                         5
crec_dllo                          5
clas_peso                          5
piel_rese                          4
e_complem                          4
menores                            4
hiperpigm                          4
ruta_atenc                         3
cod_dpto_o                         3
carne_vac                          3
delgadez                           3
gp_migrant                         2
gp_pobicbf                         2
t_lechem                           2
clas_talla                         2
edema                              2
palidez                            2
esq_vac                            1
dtype: int64

===== COLUMNAS CON NULOS 2021 =====
otra_ident                       580
otra_orien                       580
sem_ges_                         580
cer_def_                         580
fm_fuerza                        580
estrato_datos_complementarios    580
RegIniFec                        580
fm_grado                         580
cbmte_                           580
fm_unidad                        580
cen_pobla_                       538
localidad_                       490
bar_ver_                         467
seg_nom_ma                       372
peso_nac                         318
nuni_modif                       256
orient_sex                       247
uni_modif                        240
iden_gener                       216
edad_ges                         179
seg_ape_ma                       173
seg_nom_                         142
diag_medic                        67
nom_grupo_                        48
tipo_manej                        28
seg_ape_                          25
ajuste_                           17
niv_educat                        15
clas_peso                         12
estrato_                          10
menores                           10
gp_desplaz                         9
gp_migrant                         8
piel_rese                          8
delgadez                           7
gp_pobicbf                         7
clas_talla                         7
esq_vac                            7
carne_vac                          6
hiperpigm                          6
crec_dllo                          6
cod_dpto_o                         5
palidez                            5
cod_dpto_r                         5
gp_indigen                         4
gp_vic_vio                         4
e_complem                          4
gp_psiquia                         3
ruta_atenc                         3
edema                              3
peso_act                           2
t_lechem                           1
dtype: int64

===== COLUMNAS CON NULOS 2022 =====
otra_ident                       850
sem_ges_                         850
otra_orien                       850
cbmte_                           850
cer_def_                         850
fm_fuerza                        850
estrato_datos_complementarios    850
RegIniFec                        850
fm_grado                         850
fm_unidad                        850
cen_pobla_                       801
localidad_                       722
bar_ver_                         686
seg_nom_ma                       562
peso_nac                         472
orient_sex                       388
nuni_modif                       387
iden_gener                       334
uni_modif                        327
edad_ges                         288
seg_ape_ma                       284
seg_nom_                         216
diag_medic                       102
nom_grupo_                        71
tipo_manej                        55
seg_ape_                          39
ajuste_                           26
niv_educat                        22
estrato_                          16
clas_talla                        14
gp_pobicbf                        14
gp_desplaz                        14
clas_peso                         13
esq_vac                           12
gp_vic_vio                        12
gp_migrant                        11
hiperpigm                         11
piel_rese                         10
cod_dpto_o                        10
crec_dllo                          9
gp_indigen                         8
menores                            8
e_complem                          8
palidez                            7
gp_psiquia                         6
edema                              6
carne_vac                          6
cod_dpto_r                         5
t_lechem                           5
delgadez                           5
ruta_atenc                         4
zscore_te                          1
talla_act                          1
dtype: int64

===== COLUMNAS CON NULOS 2023 =====
sem_ges_                         107
otra_orien                       107
otra_ident                       107
estrato_datos_complementarios    107
RegIniFec                        107
fm_fuerza                        107
cer_def_                         107
fm_unidad                        107
fm_grado                         107
cbmte_                           107
iden_gener                       106
orient_sex                       106
cen_pobla_                       105
uni_modif                        102
nuni_modif                       102
bar_ver_                         101
localidad_                        94
lat_dir                           87
long_dir                          87
seg_nom_ma                        63
peso_nac                          54
diag_medic                        44
tipo_manej                        40
edad_ges                          33
seg_ape_ma                        32
seg_nom_                          30
vereda_                           21
nom_grupo_                        10
seg_ape_                           8
res_pr_ape                         8
telefono_                          5
gp_mad_com                         3
gp_gestan                          3
estrato_                           3
niv_educat                         2
dtype: int64

===== COLUMNAS CON NULOS 2024 =====
otra_ident         1441
fm_unidad          1441
fm_fuerza          1441
cbmte_             1441
cer_def_           1441
                   ...
zscore_te             1
ruta_atenc            1
palidez               1
cambios_cabello       1
hiperpigm             1
Length: 62, dtype: int64

===== COLUMNAS CON NULOS 2025 =====
otra_orien                       1057
otra_ident                       1057
fm_fuerza                        1057
cer_def_                         1057
cbmte_                           1057
sem_ges_                         1057
fm_grado                         1057
fm_unidad                        1057
estrato_datos_complementarios    1057
lat_dir                          1028
long_dir                         1028
cen_pobla_                       1006
localidad_                        905
bar_ver_                          869
seg_nom_ma                        641
peso_nac                          534
edad_ges                          328
orient_sex                        326
seg_ape_ma                        290
seg_nom_                          283
vereda_                           241
iden_gener                        227
telefono_                         225
res_pr_ape                        123
nom_grupo_                         97
tipo_manej                         64
diag_medic                         62
nuni_modif                         59
seg_ape_                           58
uni_modif                          28
estrato_                           16
niv_educat                         15
gp_gestan                          15
gp_mad_com                         15
gp_psiquia                          2
gp_migrant                          2
gp_indigen                          2
gp_pobicbf                          2
gp_discapa                          2
gp_desmovi                          2
gp_vic_vio                          2
gp_desplaz                          2
gp_carcela                          2
clas_peso                           2
clas_talla                          2
RegIniFec                           1
dtype: int64

### Porcentaje de datos faltantes

In [9]:
for year, df in datasets.items():
    print(f"\n===== PORCENTAJE DE NULOS {year} =====")
    
    percent = (df.isnull().sum() / len(df)) * 100
    print(percent.sort_values(ascending=False))

===== PORCENTAJE DE NULOS 2020 =====
otra_ident    100.0
otra_orien    100.0
sem_ges_      100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

===== PORCENTAJE DE NULOS 2021 =====
otra_ident    100.0
otra_orien    100.0
sem_ges_      100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

===== PORCENTAJE DE NULOS 2022 =====
otra_ident    100.0
otra_orien    100.0
sem_ges_      100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

===== PORCENTAJE DE NULOS 2023 =====
otra_ident    100.0
otra_orien    100.0
sem_ges_      100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

===== PORCENTAJE DE NULOS 2024 =====
otra_ident    100.0
sem_ges_      100.0
fm_unidad     100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

===== PORCENTAJE DE NULOS 2025 =====
otra_ident    100.0
otra_orien    100.0
sem_ges_      100.0
fm_grado      100.0
cbmte_        100.0
              ...
ndep_resi       0.0
ndep_notif      0.0
nmun_notif      0.0
FechaHora       0.0
vacio           0.0
Length: 126, dtype: float64

### Revisar duplicados

In [10]:
for year, df in datasets.items():
    print(f"\n===== DUPLICADOS DATASET {year} =====")
    print("Registros duplicados:", df.duplicated().sum())

===== DUPLICADOS DATASET 2020 =====
Registros duplicados: 0

===== DUPLICADOS DATASET 2021 =====
Registros duplicados: 0

===== DUPLICADOS DATASET 2022 =====
Registros duplicados: 0

===== DUPLICADOS DATASET 2023 =====
Registros duplicados: 0

===== DUPLICADOS DATASET 2024 =====
Registros duplicados: 0

===== DUPLICADOS DATASET 2025 =====
Registros duplicados: 0

### Ver primeras filas

In [11]:
for year, df in datasets.items():
    print(f"\n===== PRIMERAS FILAS DATASET {year} =====")
    display(df.head())

===== PRIMERAS FILAS DATASET 2020 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,28/07/2020,30,2020,4484700332,85,SEBASTIAN,NaN,MONTIEL,TORRES,RC,1217850190,3,1,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44.0,45,3,NaN,NaN,CORREGIMIENTO DE LOS REMEDIOS,NaN,RESGUARDO IROKA WAYICO,0,0,99999.07,S,EPSI01,1,WAYUU,2.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,47.0,660,26/07/2020,19/07/2020,4,1,26/07/2020,1,- -,0.0,SIN INFORMACION,27/04/2020,NaN,NaN,2.000101e+11,CENTRO DE SALUD PUEBLO BELLO,01/08/2020,SOFIA GIRALDO SISSIV[C00],3003178859,18/02/2021,896475200,NaN,NaN,NaN,Captura 1.6.46,JEAN,NaN,BOURIYU,MONTIEL,CC,283954648,5.0,2.0,NaN,0,38.0,6.0,6.0,1.0,1.0,2.0,8.36,64.80,0.0,2,14.03,-2.6953,2.0,-1.9224,2.0,2.0,2.0,1.0,1.0,1,NaN,1.0,1.0,E43X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS BECERRIL UNIDAD MOVIL,COLOMBIA,CESAR,BECERRIL,COLOMBIA,CESAR,BECERRIL,CESAR,BECERRIL,28/07/2020,NaN,0
1,113,09/11/2020,45,2020,2000100012,7,DAINELIS,NaN,EPINAYU,WEPA,RC,1354791208,1,1,170,COLOMBIA,M,NaN,NaN,1.0,NaN,170,20.0,847,3,NaN,COMUNIDAD JERUSALEN,RANCHERIA AMNAMANA KM 94 VIA CARREIPIA,ICHIEN,LA FRONTERA,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,20.0,1,11/11/2020,02/11/2020,4,1,09/11/2020,1,- -,0.0,3180635816,09/10/2020,NaN,NaN,4.484700e+11,NaN,12/11/2020,MARIA PAZ ATENCIO,3155162045,19/02/2021,954174643,NaN,NaN,NaN,Captura 1.6.45,NANCY,DEL CARMEN,IZQUIERDO,HERRERA,CC,54520941,5.0,3.0,NaN,0,38.0,6.0,9.0,1.0,2.0,2.0,7.89,64.73,18.4,3,14.35,-3.2330,2.0,-6.6697,1.0,2.0,1.0,2.0,1.0,2,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,ESE HOSPITAL SAN CRISTOBAL,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,09/11/2020,NaN,0
2,113,20/12/2020,51,2020,2000100012,1,SEYARUKWIN,PATRICIA,BRITO,GAMEZ,RC,1330914303,5,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20.0,45,3,NaN,NaN,UNKAMECHUN,9999999 SIN INFORMACION,YOWA,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,20.0,570,21/12/2020,17/12/2020,4,2,- -,1,- -,0.0,3029350082,23/07/2020,NaN,NaN,0.000000e+00,NaN,20/12/2020,MAOLIS ACOSTA BRITO,30000000,14/02/2021,984471526,NaN,NaN,NaN,Captura 1.6.45,OLGA,NaN,URIANA,PUSHAINA,CC,178101955,5.0,1.0,NaN,0,NaN,6.0,6.0,1.0,1.0,2.0,9.03,68.12,12.0,1,14.00,-3.7643,2.0,-3.1668,1.0,2.0,1.0,1.0,1.0,2,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CLINIVIDA Y SALUD IPS SAS,COLOMBIA,CESAR,BECERRIL,COLOMBIA,CESAR,BECERRIL,CESAR,BECERRIL,20/12/2020,NaN,0
3,113,09/06/2020,23,2020,4409000227,1,ELAIZA,CARLOS,PEREZ,CONCHACALA,RC,1287775687,1,1,170,COLOMBIA,M,1.0,NaN,1.0,NaN,170,20.0,847,3,NaN,NaN,SAN JOSE DE ORIENTE,NaN,SOSPA,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,44.0,13,08/06/2020,03/06/2020,4,1,06/06/2020,1,- -,0.0,SIN INFORMACION,08/05/2020,NaN,NaN,4.484701e+11,ESE HOSPITAL NUESTRA SEÑORA DEL PILAR,10/06/2020,NATHALIA FERNANDEZ,3046255498,19/02/2021,984191209,NaN,NaN,NaN,Captura 1.6.46,MAYERLIS,NaN,EPINAYU,NaN,CC,670274438,1.0,1.0,NaN,0,NaN,11.0,6.0,1.0,3.0,2.0,5.48,50.56,0.0,1,13.97,-1.5617,2.0,-4.8838,1.0,2.0,1.0,1.0,1.0,1,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,IPSI SUPULA WAYUU,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,09/06/2020,NaN,0
4,113,29/12/2020,52,2020,4484700836,5,ADA,DAVID,GONZALEZ,JUSAYU,RC,1286603046,1,2,170,COLOMBIA,F,1.0,NaN,NaN,NaN,170,44.0,847,3,NaN,NaN,BOTOIN,NaN,RESGUARDO INDIGENA MAYAMANGLOMA,0,0,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,2,170,44.0,13,26/12/2020,23/12/2020,4,2,- -,1,- -,7.0,SIN INFORMACION,27/11/2020,NaN,NaN,2.000101e+11,DUSAKAWI IPS,30/12/2020,ZARAN ROBLES,3003036038,14/02/2021,817551876,NaN,NaN,NaN,SIVIGILA - 2018 -18.6.5$0$1.0,AURA,NaN,EPIEYU,GARCIA,CC,660695908,5.0,1.0,NaN,43,NaN,10.0,7.0,2.0,3.0,2.0,9.78,57.20,14.3,1,14.57,-4.0168,2.0,-2.1655,1.0,2.0,1.0,1.0,1.0,1,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD MATERNO INFANTIL TALAPUIN SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,29/12/2020,NaN,0

===== PRIMERAS FILAS DATASET 2021 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,11/12/2021,50,2021,2057000983,1,NEIDER,DAVID,URIANA,GARCIA,RC,1307454094,1,1,170,COLOMBIA,M,2.0,NaN,1.0,NaN,170,44.0,1,3,NaN,LAS PEÑAS,LAGUNITA,NaN,LA SIERRA,0,0,99999.07,S,EPSI01,1,ARHUACO,1.0,2,NaN,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,20.0,35,13/12/2021,11/12/2021,4,1,14/12/2021,1,- -,0.0,3082150416,14/11/2021,NaN,NaN,446500071701,CENTRO DE RECUPERACION NUTRICIONAL NANAECHPO,19/12/2021,KEIDY HERRERA,3017521749,18/02/2022,887426937,NaN,NaN,NaN,Captura 1.6.46,ROSITA,NaN,MALO,WEPA,CC,765835780,5.0,1.0,3353.0,0,NaN,6.0,12.0,2.0,1.0,2.0,5.92,52.68,14.7,1,12.53,-0.2313,2.0,-4.1252,NaN,2.0,1.0,1.0,1.0,1,2.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,SOCIEDAD MEDICA SANTA MARTA SAS CLINICA PRADO,COLOMBIA,CESAR,VALLEDUPAR,COLOMBIA,CESAR,VALLEDUPAR,CESAR,VALLEDUPAR,11/12/2021,NaN,0
1,113,30/12/2021,52,2021,2000100330,5,MOISES,JOSE,SAUNA,EPIAYU,RC,1243861311,1,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20.0,430,3,NaN,NaN,RANCHERIA GERGER,NaN,CALLE 40 7H-34,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,47.0,13,30/12/2021,27/12/2021,4,1,31/12/2021,1,- -,7.0,3121939994,28/11/2021,NaN,NaN,200010098301,CENTRO DE SALUD PUEBLO BELLO,31/12/2021,CARLOS PEREZ BAQUERO,3014589333,13/02/2022,962558507,NaN,NaN,NaN,Captura 1.6.31,LICETH,NaN,EPIAYU,NaN,CC,328091180,5.0,1.0,2877.0,0,NaN,10.0,6.0,1.0,3.0,2.0,8.56,61.19,13.7,1,14.75,1.7981,2.0,-2.3016,1.0,2.0,1.0,2.0,1.0,1,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,ESE HOSPITAL ARMANDO PABON LOPEZ,COLOMBIA,GUAJIRA,MAICAO,COLOMBIA,GUAJIRA,MAICAO,GUAJIRA,MAICAO,30/12/2021,NaN,0
2,113,08/11/2021,45,2021,2000100330,1,MARIANA,ISABEL,FRAGOZO,QUINTERO,RC,1222678258,1,2,170,COLOMBIA,F,NaN,NaN,1.0,NaN,170,20.0,13,3,NaN,NaN,SOCHAYE,NaN,RACNHERIA WAJATECHON,0,0,99999.07,S,EPSI01,1,YUKPA,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,NaN,2.0,1,4,170,20.0,560,12/11/2021,05/11/2021,4,1,08/11/2021,1,- -,7.0,3050546986,10/10/2021,NaN,NaN,200139000085,NaN,12/11/2021,ENGUIMAR GOMEZ,3225366812,18/02/2022,947595576,NaN,NaN,NaN,Captura 1.6.45,WENDY,NaN,EPIEYU,NaN,CC,92593744,5.0,1.0,3163.0,44,39.0,12.0,6.0,2.0,3.0,2.0,7.12,45.00,12.9,2,13.94,-3.5945,1.0,-1.3442,1.0,2.0,1.0,1.0,2.0,1,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CLINICA DEL CESAR SA,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,AGUSTIN CODAZZI,08/11/2021,NaN,0
3,113,02/01/2021,1,2021,4407800892,5,JESUALDO,DAVID,MORALES,RAMIREZ,RC,1389716305,3,1,170,COLOMBIA,F,1.0,NaN,1.0,NaN,170,20.0,847,2,NaN,NaN,RESGUARDO IROKA ZONA NANACHPO ASENTAMIENTPO GU...,NaN,KM 35 VIA RIOHACHA,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,NaN,1,05/01/2021,31/12/2020,4,1,03/01/2021,1,- -,6.0,3238752582,07/10/2020,NaN,NaN,NaN,BAYLOR COLLEGE OF MEDICINE CHILDRENS FOUNDATIO...,08/01/2021,MAURA B SISSIV[C00],3152879890,17/02/2022,983410778,NaN,NaN,NaN,Captura 2.0.5,SAIRITA,NaN,CHINCHILLA,MEJIA,CC,346470660,5.0,1.0,NaN,0,39.0,6.0,7.0,1.0,1.0,1.0,8.82,80.33,13.1,1,11.23,-2.9329,2.0,-3.0929,1.0,2.0,1.0,2.0,2.0,2,1.0,1.0,1.0,E43X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CENTRO DE SALUD PUEBLO BELLO,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,02/01/2021,NaN,0
4,113,10/08/2021,32,2021,4443000821,1,JUAN,LISETH,MORALES,MOLINA,RC,1335832391,3,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,44.0,570,3,URIBIA,NaN,ALESAPOULIA,NaN,MAISHEN - CARDON,0,0,99999.07,S,EPSI01,6,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,44.0,13,11/08/2021,05/08/2021,4,2,- -,1,- -,7.0,3027992191,12/05/2021,NaN,NaN,NaN,NaN,17/08/2021,ALFREDO RAUL CALDERON VIÑA SISSIV[C00],3135727785,16/02/2022,967149357,NaN,NaN,NaN,Captura 1.6.46,DIANA,MATLDE,YEPES,NaN,CC,1192251999,5.0,1.0,NaN,42,41.0,8.0,6.0,2.0,2.0,2.0,9.64,52.14,1.6,1,15.23,-3.1654,1.0,-5.5299,1.0,2.0,1.0,2.0,1.0,1,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,IPSI SUPULA WAYUU URIBIA,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,10/08/2021,NaN,0

===== PRIMERAS FILAS DATASET 2022 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,26/10/2022,43,2022,4443000168,1,AARON,DAVID,GARCIA,GONZALEZ,RC,1321969348,1,2,170,COLOMBIA,F,2.0,NaN,2.0,NaN,170,20.0,847,3,NaN,NaN,GUAYAVITEL,NaN,KILOMETRO 29 VIA MAICAO SANTA CRUZ,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,20.0,1,29/10/2022,24/10/2022,4,2,- -,1,- -,0.0,3288515545,26/09/2022,NaN,NaN,NaN,UNIDAD MEDICA WAYUU ANOUTA WAKUAIPA IPSI,26/10/2022,HELEN ARAGON SISSIV[1000000C00],5712339,17/02/2023,818073679,NaN,NaN,NaN,Captura 1.6.31,SELENA,NaN,EPIEYU,NaN,CC,425086767,5.0,1.0,2551.0,0,NaN,12.0,6.0,2.0,1.0,2.0,6.69,69.31,13.7,3,15.98,-2.9979,3.0,-4.0158,1.0,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD MATERNO INFANTIL TALAPUIN SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,26/10/2022,NaN,0
1,113,28/03/2022,13,2022,4443000277,2,YASMIN,NaN,EPIEYU,ZAPUANA,RC,1371967684,1,2,170,COLOMBIA,F,1.0,NaN,NaN,NaN,170,44.0,1,3,NaN,NaN,KAWAMANA-VIA CERRO LA TETA,NaN,VEREDA CAMPECHE,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,20.0,430,29/03/2022,30/03/2022,4,2,- -,1,- -,0.0,3233864135,28/02/2022,NaN,NaN,2.000100e+11,OUTTAJIAPULEE IPSI,01/04/2022,KAREN DEL VALLE,3008856129,19/02/2023,850787721,NaN,NaN,NaN,Captura 1.6.45,JESSICA,ISABEL,DINGULA,NaN,CC,290741387,1.0,1.0,NaN,0,NaN,1.0,6.0,2.0,1.0,2.0,6.84,60.21,13.0,1,14.43,-2.8992,2.0,-0.8628,1.0,2.0,1.0,1.0,1.0,1,1.0,1.0,NaN,NaN,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS,COLOMBIA,CESAR,VALLEDUPAR,COLOMBIA,CESAR,VALLEDUPAR,CESAR,VALLEDUPAR,28/03/2022,NaN,0
2,113,05/09/2022,36,2022,4443000168,85,MISHEL,DANIEL,ARGOTE,FERNANDEZ,RC,1257830846,1,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20.0,847,2,NaN,SIERRA,KASPAICHI-TAPARAJIN,NaN,APONSYA,0,0,99999.07,S,EPSI01,6,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,2,170,47.0,1,06/09/2022,09/09/2022,4,1,06/09/2022,1,- -,6.0,3285937623,08/08/2022,NaN,NaN,NaN,ESE HOSPITAL SAN JOSE DE MAICAO,08/09/2022,ALFREDO RAUL CALDERON VIÑA,3216843503,15/02/2023,928707814,NaN,NaN,NaN,Captura 2.0.1,PAOLA,VIRGINIA,EPIAYU,PAZ,CC,471551402,NaN,1.0,2824.0,0,38.0,24.0,16.0,1.0,1.0,2.0,5.06,65.97,11.9,3,14.43,2.0807,2.0,-5.8050,2.0,1.0,2.0,1.0,NaN,1,1.0,1.0,1.0,E43X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,IPSI SUPULA WAYUU,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,05/09/2022,NaN,0
3,113,27/05/2022,21,2022,2001390000,1,KATERIN,CAROLINA,PUSHAINA,RODRIGUEZ,RC,1293499481,7,2,170,COLOMBIA,F,1.0,NaN,1.0,NaN,170,20.0,847,1,NaN,NaN,RANCHERI MACHOMANA,NaN,INVASION NUEVA ESPERANZA,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,2,1,170,20.0,1,28/05/2022,24/05/2022,4,1,25/05/2022,1,- -,0.0,3133755521,27/10/2021,NaN,NaN,2.000100e+11,HOSPITAL SAN RAFAEL NIVEL II,30/05/2022,SAMIR URBAY,3014589333,16/02/2023,956419546,NaN,NaN,NaN,Captura 1.6.31,MARIA,NaN,JUSAYU,PADILLA,CC,968802921,2.0,5.0,NaN,0,NaN,24.0,6.0,2.0,1.0,2.0,11.62,62.59,14.3,3,13.97,-3.3745,1.0,-5.6457,NaN,2.0,1.0,2.0,1.0,2,1.0,1.0,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,SOCIEDAD MEDICA CLINICA MAICAO LTDA,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,27/05/2022,NaN,0
4,113,13/03/2022,11,2022,2001390000,1,JOSE,KARINA,PUSHAINA,PUSHAINA,RC,1336312714,1,2,170,COLOMBIA,M,1.0,NaN,1.0,NaN,170,20.0,1,3,NaN,NaN,MESTHA,NaN,MANAURE,0,0,99999.07,S,EPSI01,1,WAYUU,1.0,2,2.0,2.0,2,2,NaN,2.0,2.0,2,2,2.0,2.0,1,1,170,20.0,13,19/03/2022,15/03/2022,4,1,15/03/2022,1,- -,0.0,3233126482,14/02/2022,NaN,NaN,4.484701e+11,NaN,21/03/2022,KELLYS DAYANA CAMPO VILLA SISSIV[C00],3174662742,17/02/2023,988171300,NaN,NaN,NaN,Captura 1.6.45,FREDY,DEL CARMEN,URIANA,NaN,CC,150393751,5.0,2.0,NaN,0,NaN,6.0,6.0,1.0,1.0,1.0,3.67,64.60,13.0,3,14.42,-2.7219,2.0,-2.9281,1.0,2.0,1.0,2.0,1.0,1,2.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,GYO MEDICAL IPS SAS,COLOMBIA,CESAR,VALLEDUPAR,COLOMBIA,CESAR,VALLEDUPAR,CESAR,VALLEDUPAR,13/03/2022,NaN,0

===== PRIMERAS FILAS DATASET 2023 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,10/01/2023,2,2023,4484700677,2,ELIENDER,SEGUNDO,IPUANA,GONZALEZ,RC,1124557354,6,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA TOSPA,NaN,RANCHERIA TOSPA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,10/01/2023,- -,4,2,- -,1,- -,7,3216532684,29/06/2022,NaN,NaN,NaN,NaN,- -,JOSE JAIME ALVAREZ,3005323756,20/02/2024,9001913221,NaN,NaN,NaN,Captura 1.6.31,MAGALIS,NaN,GONZALEZ,IPUANA,CC,27033702,5.0,1,2620.0,47,38.0,10,4,1,1,1,5,60,"11,5",1.0,"13,89","-2,2374",2,"-3,562",1,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,OUTTAJIAPULEE IPSI,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,20/02/2024,NaN,0
1,113,09/05/2023,19,2023,4400100441,1,ILDER,NaN,ARPUSIANA,PUSHAINA,RC,1225074831,1,1,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,1,3,NaN,NaN,COMUNIDAD MAZOYA,NaN,VIA SANTA MARTA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,NaN,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,1,09/05/2023,06/05/2023,4,1,09/05/2023,1,- -,7,3003713246,26/01/2022,NaN,NaN,NaN,NaN,- -,MARIA PAULA TORRES OLMOS,7282809,20/02/2024,825003806,NaN,NaN,NaN,Captura 1.6.31,DORIS,NaN,PUSHAINA,NaN,CC,40933715,5.0,2,2210.0,43,NaN,6,12,1,1,2,"4,6",56,"10,3",3.0,"14,7","-0,586",4,"-9,1475",1,2,1,1,1,1,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD DE CUIDADOS INTENSIVOS RENACER,COLOMBIA,GUAJIRA,RIOHACHA,COLOMBIA,GUAJIRA,RIOHACHA,GUAJIRA,RIOHACHA,20/02/2024,NaN,0
2,113,08/05/2023,19,2023,4484700836,1,DEINER,JOSE,EPIEYU,NaN,RC,1124557968,1,1,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA SARIJANOU,NaN,RANCHERIA WARIJANOU,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,08/05/2023,01/05/2023,4,1,08/05/2023,1,- -,7,3148079349,13/04/2022,NaN,NaN,NaN,NaN,- -,LUIS MIGUEL IGUARAN,3108313376,20/02/2024,900492815,NaN,NaN,NaN,Captura 1.6.31,MILEIDY,NaN,EPIAYU,NaN,CC,1151458545,1.0,2,NaN,0,38.0,6,6,1,1,1,"7,4","71,5","12,1",3.0,"14,5","-2,1066",2,"-1,788",2,2,1,2,2,1,2,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD MATERNO INFANTIL TALAPUIN SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,20/02/2024,NaN,0
3,113,04/10/2023,40,2023,2057000983,5,DWIA,RUKUNGUMU,MEJIA,CRESPO,RC,1063604976,10,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,SIMONORWA,NaN,SIMONORWA,NaN,NaN,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,04/10/2023,04/08/2023,4,2,- -,1,- -,7,SIN INFORMACIÓN,24/11/2022,NaN,NaN,NaN,NaN,- -,DANIELA BURGOS,3128439725,20/02/2024,9000736458,NaN,NaN,NaN,Captura 1.6.31,GUNEIWIA,NaN,CRESPO,TORRES,CC,1148197258,5.0,1,NaN,0,40.0,6,6,1,3,2,"7,3",72,13,1.0,"14,1","-2,4425",2,"-0,5607",3,2,1,2,1,1,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CENTRO DE SALUD PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,20/02/2024,NaN,0
4,113,11/05/2023,19,2023,2057000236,1,KARILIS,LICET,NIÑO,TORRES,RC,1063604045,1,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,"PALM,ARITO",NaN,PALMARITO,NaN,NaN,99999.07,S,EPSI01,6,NaN,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,11/05/2023,01/03/2023,4,1,11/05/2023,1,- -,7,SIN INFORMACIÓN,11/03/2022,NaN,NaN,NaN,NaN,- -,ANNY BAYONA,3165200035,22/02/2024,8240026728,NaN,NaN,NaN,Captura 1.6.31,JOHINER,DURAWINO,NIÑO,ARROYO,CC,113984904,1.0,1,NaN,0,NaN,6,6,2,1,2,"7,3","70,5",6,3.0,"14,7","-1,4033",3,"-2,1914",1,1,1,1,1,1,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,ESE HOSPITAL CAMILO VILLAZON PUMAREJO,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,22/02/2024,NaN,0

===== PRIMERAS FILAS DATASET 2024 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,19/01/2024,3,2024,2001301346,2,KELLY,NONE,FRANCO,PEREZ,RC,1300422455,1,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,13,1,NaN,NaN,NaN,9999999 SIN INFORMACION,ASENTAMIENTO NEIPO,0.0,0.0,9999.00,S,EPSI01,1,YUKPA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,13,17/01/2024,15/01/2024,4,1,17/01/2024,1,- -,0,SIN INFORMACION,22/12/2022,NaN,NaN,NaN,NaN,21/01/2024,MARIA DAVID,3003715918,19/01/2024,9003457651,NaN,NaN,NaN,SIVIGILA - 2018 -18.4.3$0$0.0,LIDIA,NONE,PEREZ,PEÑALOZA,CC,1133485557,5.0,1.0,2500.0,49.0,39.0,6.0,12.0,1.0,3.0,2.0,"6,5",69,12,NaN,"13,65","-2,3146",2.0,"-1,9476",2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CLINICA CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,AGUSTIN CODAZZI,21/01/2024,NaN,0
1,113,06/01/2024,1,2024,2000101794,1,RUMALDA,NaN,ARROYO,COTES,RC,1063604975,2,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,570,1,NaN,NaN,NaN,CASA INDIGENA,CASA INIDIGENA,0.0,0.0,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,06/01/2024,04/01/2023,4,1,06/01/2024,1,- -,0,3113527221,10/01/2022,NaN,NaN,NaN,NaN,16/01/2024,GUILLERMO MARTINEZ,0,13/01/2024,9006010527,NaN,NaN,NaN,SIVIGILA - 2018 -18.6.5$0$0.0,MAMA DE RUMALDA,NaN,COSTES,NaN,CC,1148140406,5.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,"7,8",70,13,3.0,"15,92","-0,506",4.0,"-4,8903",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD PEDIATRICA SIMON BOLIVAR,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,VALLEDUPAR,16/01/2024,NaN,0
2,113,15/03/2024,11,2024,2000100012,1,YAIR,HERNANDO,MONTES,GARCIA,RC,1300421976,10,2,170,COLOMBIA,M,1.0,NaN,1.0,NaN,170,20,13,3,NaN,NaN,EL LIMON,NaN,EL LIMON,NaN,NaN,99999.07,S,EPSI01,1,YUKPA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,13,15/03/2024,02/03/2024,4,1,16/03/2024,1,- -,0,NaN,27/04/2023,NaN,NaN,NaN,NaN,- -,EDER GAMEZMENDOZA SISSIV[C00],5804440,16/03/2024,8240023621,NaN,NaN,NaN,Captura 1.6.31,ESMERALDA,NaN,GARCIA,PEÑA,CC,1010092024,5.0,0.0,NaN,0.0,NaN,10.0,6.0,2.0,3.0,2.0,"6,5",68,11,1.0,"14,1","-2,5691",2.0,"-2,3113",1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,VALLEDUPAR,16/03/2024,NaN,0
3,113,15/01/2024,3,2024,4484700332,1,GERARDO,JOSE,URIANA,PUSHAINA,RC,1124558195,1,1,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,COMUNIDAD PERROUTALIAMANA,NaN,COMUNIDAD PERROUTALIMANA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,1,2,2,2,2.0,NaN,2,2,2.0,2,2,2,2,1,170,44,847,15/01/2024,- -,4,2,- -,1,- -,0,SIN INFORMACIÓN,04/09/2022,NaN,NaN,NaN,NaN,- -,ANGIE MONTALVO SISSIV[C00],3013950445,18/01/2024,8000617659,NaN,NaN,NaN,Captura 1.6.31,PIDELINA,NaN,URIANA,PUSHAINA,CC,1147940070,1.0,1.0,2745.0,49.0,38.0,6.0,6.0,1.0,1.0,1.0,"7,4","72,5",12,1.0,"14,1","-2,4222",2.0,"-2,9838",1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,HOSPITAL NUESTRA SEÑORA DEL PERPETUO SOCORRO,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,18/01/2024,NaN,0
4,113,04/01/2024,1,2024,2000100012,1,LUZ,ADIELA,WEPA,ESTRADA,RC,1067737278,1,1,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,13,3,NaN,NaN,NANAESCHPO,NaN,NANAESCHPO,NaN,NaN,99999.07,S,EPSI01,1,YUKPA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,13,03/01/2024,25/12/2023,4,1,04/01/2024,1,- -,0,31455274603,23/12/2022,NaN,NaN,NaN,NaN,- -,CARLOS MARIO RODRIGUEZ,5804440,04/01/2024,8240023621,NaN,NaN,NaN,Captura 1.6.31,VANESA,NaN,ESTRADA,ESTRADA,AS,1508627265733,5.0,2.0,NaN,0.0,NaN,12.0,6.0,2.0,3.0,2.0,"8,1",72,0,3.0,"15,6","-0,6277",4.0,"-0,7825",3.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,E43X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,VALLEDUPAR,04/01/2024,NaN,0

===== PRIMERAS FILAS DATASET 2025 =====

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,11/01/2025,2,2025,2000100012,1,SHAIRA,ANGELA,HERRERA,ESTRADA,RC,1133485771,1,1,170,COLOMBIA,F,2.0,NaN,1.0,NaN,170,20,13,3,NaN,NaN,NANESCHPO,NaN,NANESCHPO,NaN,NaN,99999.07,S,EPSI01,1,YUKPA,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,20,13,11/01/2025,10/01/2025,4,1,12/01/2025,1,- -,0,SIN INFORMACIÓN,27/11/2023,NaN,NaN,200010001201,DUSAKAWI IPS,- -,MARIA LAURA ARIAS,5804440,14/01/2025,8240023621,NaN,NaN,NaN,Captura 2.0.5,MERLY,NaN,ESTRADA,ESTRADA,TI,1214468379,5.0,0,2500.0,0,39.0,13,6,2,3,2,"6,8",70,11,3.0,"13,9","-2,0869",2.0,"-1,9842",2.0,2,1,1,1,1,2,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS,COLOMBIA,CESAR,AGUSTIN CODAZZI,COLOMBIA,CESAR,AGUSTIN CODAZZI,CESAR,VALLEDUPAR,14/01/2025,14/01/2025,0
1,113,09/01/2025,2,2025,4484700351,2,SHAROL,PATRICIA,FERNANDEZ,NaN,RC,1131082275,7,2,170,COLOMBIA,F,2.0,NaN,1.0,NaN,170,44,847,3,NaN,NaN,SUCARAMANA,NaN,CORREGIMIENTO IRRAIPA RANCHERIA SUCARAMANA CER...,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,09/01/2025,04/01/2025,4,2,- -,1,- -,7,3137472383,28/05/2024,NaN,NaN,448470035102,IPSI SUPULA WAYUU URIBIA,- -,DANIELA HUMANEZ,3017817650,11/01/2025,8250031495,NaN,NaN,NaN,Captura 2.0.5,DAILIS,NaN,JUSAYU,NaN,CC,1147949535,2.0,1,2800.0,40,38.0,7,7,1,1,1,"5,2","61,5","11,5",1.0,"13,7","-2,0879",2.0,"-2,4995",1.0,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,IPSI SUPULA WAYUU URIBIA,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,11/01/2025,09/01/2025,0
2,113,10/01/2025,2,2025,4484700332,1,AMAURY,DE JESUS,FINCE,EPIEYU,RC,1124563067,1,1,170,COLOMBIA,M,1.0,NaN,1.0,NaN,170,44,847,3,NaN,NaN,COMUNIDAD WAJALECHON,NaN,COMUNIDAD WAJALECHON VIA POPORTIN,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,10/01/2025,- -,4,2,- -,1,- -,0,SIN INFORMACIÓN,19/07/2023,NaN,NaN,448470033201,HOSPITAL NUESTRA SEÑORA DEL PERPETUO SOCORRO,- -,KASANDRA SOLANO,3044704970,14/01/2025,8000617659,NaN,NaN,NaN,Captura 2.0.5,SANDRA,YULIANA,EPIEYU,NaN,CC,1124358430,1.0,1,2750.0,50,39.0,14,6,1,1,2,"7,85",75,"12,5",1.0,14,"-2,3833",2.0,"-2,3664",1.0,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,HOSPITAL NUESTRA SEÑORA DEL PERPETUO SOCORRO,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,14/01/2025,14/01/2025,0
3,113,05/01/2025,2,2025,4484701173,1,MILEIXY,MILENA,URIANA,PUSHAINA,RC,114037675,2,1,170,COLOMBIA,F,2.0,NaN,NaN,NaN,170,44,847,3,NaN,NaN,ICHICHO,NaN,VEREDA ICHICHO KM 134 VIA PUERTO BOLIVAR,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,05/01/2025,01/01/2025,4,2,- -,1,- -,D,SIN INFORMACIÓN,01/08/2022,NaN,NaN,448470117301,CENTRO MEDICO COLSANITAS PREMIUM PUERTO BOLIVAR,- -,HUMBERTO GONZALEZ PEÑA,3126124609,27/01/2025,901041691,NaN,NaN,NaN,Captura 2.0.4,MARIANITA,NaN,PUSHAINA,IPUANA,CC,56100875,5.0,1,NaN,0,NaN,12,6,2,3,2,"8,3",79,13,3.0,"13,3","-2,1944",2.0,"-3,1311",1.0,2,1,1,2,2,2,2,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CENTRO MEDICO COLSANITAS PREMIUM PUERTO BOLIVAR,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,27/01/2025,06/01/2025,0
4,113,10/01/2025,2,2025,4484700351,2,FRANYIMAR,ELENA,CASTILLO,JUSAYU,RC,1245829963,1,1,170,COLOMBIA,F,2.0,NaN,1.0,NaN,170,44,847,1,URIBIA,NaN,NaN,AIPIAMANA,BARRIO AIPIAMANA POR LA TIENDA ANTONELLA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1,1,170,44,847,10/01/2025,02/01/2025,4,2,- -,1,- -,0,3135168265,31/07/2023,NaN,NaN,448470035102,IPSI SUPULA WAYUU URIBIA,- -,MARIA KARINA ESCORCIA,3014589333,07/02/2025,8250031495,NaN,NaN,NaN,Captura 2.0.8,MARIA,ZUNILDA,JUSAYU,PUSHAINA,CC,1006917401,1.0,1,3000.0,49,39.0,12,8,1,1,1,"7,4",74,"13,5",1.0,"13,5","-2,201",2.0,"-1,9905",2.0,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,IPSI SUPULA WAYUU URIBIA,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,07/02/2025,07/02/2025,0

### Comparar si las columnas son iguales entre datasets

In [12]:
common_cols = set.intersection(*(set(df.columns) for df in datasets.values()))
print("Columnas comunes a todos los años:", len(common_cols))
print(sorted(common_cols)[:30])
for year, df in datasets.items():
    unique_cols = set(df.columns) - common_cols
    print(f"{year}: columnas únicas = {len(unique_cols)}")
    if unique_cols:
        print(sorted(unique_cols)[:10])

Columnas comunes a todos los años: 126
['FechaHora', 'RegIniFec', 'ajuste_', 'area_', 'año', 'bar_ver_', 'cambios_cabello', 'carne_vac', 'cbmte_', 'cen_pobla_', 'cer_def_', 'clas_peso', 'clas_talla', 'cod_ase_', 'cod_dpto_o', 'cod_dpto_r', 'cod_eve', 'cod_mun_o', 'cod_mun_r', 'cod_pais_o', 'cod_pais_r', 'cod_pre', 'cod_sub', 'con_fin_', 'crec_dllo', 'delgadez', 'diag_medic', 'dir_res_', 'e_complem', 'edad_']
2020: columnas únicas = 0
2021: columnas únicas = 0
2022: columnas únicas = 0
2023: columnas únicas = 0
2024: columnas únicas = 0
2025: columnas únicas = 0

# ====== Variable Objetivo ======

In [13]:
for year, df in datasets.items():
    print(f"\n=== {year} ===")
    for col in df.columns:
        print(col, "-", df[col].nunique())

=== 2020 ===
cod_eve - 1
fec_not - 205
semana - 51
año - 1
cod_pre - 60
cod_sub - 13
pri_nom_ - 231
seg_nom_ - 111
pri_ape_ - 107
seg_ape_ - 101
tip_ide_ - 1
num_ide_ - 320
edad_ - 11
uni_med_ - 3
nacionali_ - 2
nombre_nacionalidad - 1
sexo_ - 2
iden_gener - 3
otra_ident - 0
orient_sex - 2
otra_orien - 0
cod_pais_o - 1
cod_dpto_o - 6
cod_mun_o - 20
area_ - 3
localidad_ - 14
cen_pobla_ - 14
vereda_ - 227
bar_ver_ - 53
dir_res_ - 250
lat_dir - 1
long_dir - 1
ocupacion_ - 3
tip_ss_ - 2
cod_ase_ - 1
per_etn_ - 3
nom_grupo_ - 7
estrato_ - 3
gp_discapa - 1
gp_desplaz - 2
gp_migrant - 2
gp_carcela - 1
gp_gestan - 1
sem_ges_ - 0
gp_indigen - 2
gp_pobicbf - 2
gp_mad_com - 1
gp_desmovi - 1
gp_psiquia - 1
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_pais_r - 1
cod_dpto_r - 5
cod_mun_r - 21
fec_con_ - 207
ini_sin_ - 210
tip_cas_ - 1
pac_hos_ - 2
fec_hos_ - 159
con_fin_ - 1
fec_def_ - 1
ajuste_ - 3
telefono_ - 260
fecha_nto_ - 151
cer_def_ - 0
cbmte_ - 0
uni_modif - 43
nuni_modif - 44
fec_arc_xl - 206
nom_dil_f_ - 237
tel_dil_f_ - 176
fec_aju_ - 7
nit_upgd - 320
fm_fuerza - 0
fm_unidad - 0
fm_grado - 0
version - 13
pri_nom_ma - 215
seg_nom_ma - 65
pri_ape_ma - 128
seg_ape_ma - 87
tip_ide_ma - 1
num_ide_ma - 320
niv_educat - 5
menores - 6
peso_nac - 122
talla_nac - 25
edad_ges - 16
t_lechem - 26
e_complem - 16
crec_dllo - 2
esq_vac - 3
carne_vac - 2
peso_act - 267
talla_act - 289
per_braqui - 87
res_pr_ape - 3
imc - 244
zscore_pt - 316
clas_peso - 6
zscore_te - 318
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 8
estrato_datos_complementarios - 0
nom_eve - 1
nom_upgd - 60
npais_proce - 1
ndep_proce - 3
nmun_proce - 19
npais_resi - 1
ndep_resi - 3
nmun_resi - 19
ndep_notif - 3
nmun_notif - 19
FechaHora - 205
RegIniFec - 0
vacio - 1

=== 2021 ===
cod_eve - 1
fec_not - 272
semana - 52
año - 1
cod_pre - 68
cod_sub - 13
pri_nom_ - 345
seg_nom_ - 175
pri_ape_ - 141
seg_ape_ - 132
tip_ide_ - 1
num_ide_ - 580
edad_ - 11
uni_med_ - 3
nacionali_ - 2
nombre_nacionalidad - 1
sexo_ - 2
iden_gener - 3
otra_ident - 0
orient_sex - 2
otra_orien - 0
cod_pais_o - 1
cod_dpto_o - 6
cod_mun_o - 24
area_ - 3
localidad_ - 22
cen_pobla_ - 30
vereda_ - 367
bar_ver_ - 80
dir_res_ - 418
lat_dir - 1
long_dir - 1
ocupacion_ - 4
tip_ss_ - 2
cod_ase_ - 1
per_etn_ - 3
nom_grupo_ - 8
estrato_ - 3
gp_discapa - 1
gp_desplaz - 2
gp_migrant - 2
gp_carcela - 1
gp_gestan - 1
sem_ges_ - 0
gp_indigen - 2
gp_pobicbf - 2
gp_mad_com - 1
gp_desmovi - 1
gp_psiquia - 1
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_pais_r - 1
cod_dpto_r - 7
cod_mun_r - 22
fec_con_ - 281
ini_sin_ - 287
tip_cas_ - 1
pac_hos_ - 2
fec_hos_ - 216
con_fin_ - 1
fec_def_ - 1
ajuste_ - 4
telefono_ - 447
fecha_nto_ - 190
cer_def_ - 0
cbmte_ - 0
uni_modif - 56
nuni_modif - 49
fec_arc_xl - 295
nom_dil_f_ - 358
tel_dil_f_ - 266
fec_aju_ - 7
nit_upgd - 580
fm_fuerza - 0
fm_unidad - 0
fm_grado - 0
version - 14
pri_nom_ma - 332
seg_nom_ma - 106
pri_ape_ma - 176
seg_ape_ma - 121
tip_ide_ma - 1
num_ide_ma - 580
niv_educat - 5
menores - 7
peso_nac - 186
talla_nac - 31
edad_ges - 23
t_lechem - 30
e_complem - 16
crec_dllo - 2
esq_vac - 3
carne_vac - 2
peso_act - 438
talla_act - 503
per_braqui - 100
res_pr_ape - 3
imc - 363
zscore_pt - 574
clas_peso - 7
zscore_te - 579
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 9
estrato_datos_complementarios - 0
nom_eve - 1
nom_upgd - 63
npais_proce - 1
ndep_proce - 3
nmun_proce - 21
npais_resi - 1
ndep_resi - 3
nmun_resi - 21
ndep_notif - 3
nmun_notif - 21
FechaHora - 272
RegIniFec - 0
vacio - 1

=== 2022 ===
cod_eve - 1
fec_not - 325
semana - 52
año - 1
cod_pre - 73
cod_sub - 16
pri_nom_ - 440
seg_nom_ - 208
pri_ape_ - 165
seg_ape_ - 148
tip_ide_ - 1
num_ide_ - 850
edad_ - 12
uni_med_ - 3
nacionali_ - 2
nombre_nacionalidad - 1
sexo_ - 2
iden_gener - 3
otra_ident - 0
orient_sex - 3
otra_orien - 0
cod_pais_o - 1
cod_dpto_o - 7
cod_mun_o - 27
area_ - 3
localidad_ - 27
cen_pobla_ - 30
vereda_ - 424
bar_ver_ - 99
dir_res_ - 526
lat_dir - 1
long_dir - 1
ocupacion_ - 5
tip_ss_ - 2
cod_ase_ - 1
per_etn_ - 3
nom_grupo_ - 7
estrato_ - 3
gp_discapa - 1
gp_desplaz - 2
gp_migrant - 2
gp_carcela - 1
gp_gestan - 1
sem_ges_ - 0
gp_indigen - 2
gp_pobicbf - 2
gp_mad_com - 1
gp_desmovi - 1
gp_psiquia - 1
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_pais_r - 1
cod_dpto_r - 6
cod_mun_r - 24
fec_con_ - 325
ini_sin_ - 318
tip_cas_ - 1
pac_hos_ - 2
fec_hos_ - 270
con_fin_ - 1
fec_def_ - 1
ajuste_ - 4
telefono_ - 673
fecha_nto_ - 238
cer_def_ - 0
cbmte_ - 0
uni_modif - 66
nuni_modif - 58
fec_arc_xl - 316
nom_dil_f_ - 487
tel_dil_f_ - 315
fec_aju_ - 7
nit_upgd - 850
fm_fuerza - 0
fm_unidad - 0
fm_grado - 0
version - 18
pri_nom_ma - 438
seg_nom_ma - 122
pri_ape_ma - 202
seg_ape_ma - 149
tip_ide_ma - 1
num_ide_ma - 850
niv_educat - 5
menores - 10
peso_nac - 260
talla_nac - 31
edad_ges - 23
t_lechem - 29
e_complem - 19
crec_dllo - 2
esq_vac - 3
carne_vac - 2
peso_act - 560
talla_act - 708
per_braqui - 122
res_pr_ape - 3
imc - 433
zscore_pt - 831
clas_peso - 7
zscore_te - 840
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 10
estrato_datos_complementarios - 0
nom_eve - 1
nom_upgd - 75
npais_proce - 1
ndep_proce - 4
nmun_proce - 24
npais_resi - 1
ndep_resi - 4
nmun_resi - 24
ndep_notif - 4
nmun_notif - 24
FechaHora - 325
RegIniFec - 0
vacio - 1

=== 2023 ===
cod_eve - 1
fec_not - 82
semana - 42
año - 1
cod_pre - 41
cod_sub - 11
pri_nom_ - 89
seg_nom_ - 53
pri_ape_ - 57
seg_ape_ - 46
tip_ide_ - 3
num_ide_ - 96
edad_ - 11
uni_med_ - 3
nacionali_ - 1
nombre_nacionalidad - 1
sexo_ - 2
iden_gener - 1
otra_ident - 0
orient_sex - 1
otra_orien - 0
cod_pais_o - 1
cod_dpto_o - 3
cod_mun_o - 12
area_ - 3
localidad_ - 8
cen_pobla_ - 2
vereda_ - 69
bar_ver_ - 6
dir_res_ - 93
lat_dir - 2
long_dir - 2
ocupacion_ - 2
tip_ss_ - 1
cod_ase_ - 1
per_etn_ - 2
nom_grupo_ - 6
estrato_ - 2
gp_discapa - 1
gp_desplaz - 1
gp_migrant - 1
gp_carcela - 1
gp_gestan - 1
sem_ges_ - 0
gp_indigen - 1
gp_pobicbf - 2
gp_mad_com - 1
gp_desmovi - 1
gp_psiquia - 1
gp_vic_vio - 1
gp_otros - 2
fuente_ - 4
cod_pais_r - 1
cod_dpto_r - 4
cod_mun_r - 13
fec_con_ - 83
ini_sin_ - 78
tip_cas_ - 1
pac_hos_ - 2
fec_hos_ - 40
con_fin_ - 1
fec_def_ - 1
ajuste_ - 4
telefono_ - 56
fecha_nto_ - 91
cer_def_ - 0
cbmte_ - 0
uni_modif - 4
nuni_modif - 4
fec_arc_xl - 8
nom_dil_f_ - 81
tel_dil_f_ - 70
fec_aju_ - 25
nit_upgd - 37
fm_fuerza - 0
fm_unidad - 0
fm_grado - 0
version - 8
pri_nom_ma - 92
seg_nom_ma - 34
pri_ape_ma - 56
seg_ape_ma - 44
tip_ide_ma - 5
num_ide_ma - 96
niv_educat - 4
menores - 7
peso_nac - 22
talla_nac - 12
edad_ges - 10
t_lechem - 18
e_complem - 12
crec_dllo - 2
esq_vac - 3
carne_vac - 2
peso_act - 60
talla_act - 53
per_braqui - 23
res_pr_ape - 3
imc - 62
zscore_pt - 98
clas_peso - 7
zscore_te - 99
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 5
estrato_datos_complementarios - 0
nom_eve - 1
nom_upgd - 41
npais_proce - 1
ndep_proce - 3
nmun_proce - 14
npais_resi - 1
ndep_resi - 4
nmun_resi - 15
ndep_notif - 5
nmun_notif - 14
FechaHora - 25
RegIniFec - 0
vacio - 1

=== 2024 ===
cod_eve - 1
fec_not - 326
semana - 52
año - 1
cod_pre - 87
cod_sub - 18
pri_nom_ - 745
seg_nom_ - 314
pri_ape_ - 227
seg_ape_ - 211
tip_ide_ - 5
num_ide_ - 1096
edad_ - 16
uni_med_ - 3
nacionali_ - 2
nombre_nacionalidad - 2
sexo_ - 2
iden_gener - 3
otra_ident - 0
orient_sex - 3
otra_orien - 2
cod_pais_o - 2
cod_dpto_o - 7
cod_mun_o - 28
area_ - 3
localidad_ - 51
cen_pobla_ - 66
vereda_ - 694
bar_ver_ - 186
dir_res_ - 1076
lat_dir - 2
long_dir - 2
ocupacion_ - 5
tip_ss_ - 2
cod_ase_ - 2
per_etn_ - 3
nom_grupo_ - 8
estrato_ - 3
gp_discapa - 2
gp_desplaz - 2
gp_migrant - 2
gp_carcela - 1
gp_gestan - 1
sem_ges_ - 0
gp_indigen - 2
gp_pobicbf - 2
gp_mad_com - 1
gp_desmovi - 1
gp_psiquia - 1
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_pais_r - 2
cod_dpto_r - 7
cod_mun_r - 28
fec_con_ - 332
ini_sin_ - 351
tip_cas_ - 1
pac_hos_ - 2
fec_hos_ - 272
con_fin_ - 1
fec_def_ - 1
ajuste_ - 5
telefono_ - 635
fecha_nto_ - 737
cer_def_ - 0
cbmte_ - 0
uni_modif - 78
nuni_modif - 73
fec_arc_xl - 21
nom_dil_f_ - 927
tel_dil_f_ - 553
fec_aju_ - 331
nit_upgd - 79
fm_fuerza - 0
fm_unidad - 0
fm_grado - 0
version - 21
pri_nom_ma - 797
seg_nom_ma - 224
pri_ape_ma - 318
seg_ape_ma - 222
tip_ide_ma - 10
num_ide_ma - 1153
niv_educat - 5
menores - 10
peso_nac - 202
talla_nac - 22
edad_ges - 19
t_lechem - 35
e_complem - 19
crec_dllo - 2
esq_vac - 3
carne_vac - 2
peso_act - 187
talla_act - 253
per_braqui - 65
res_pr_ape - 3
imc - 155
zscore_pt - 927
clas_peso - 7
zscore_te - 984
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 9
estrato_datos_complementarios - 0
nom_eve - 1
nom_upgd - 89
npais_proce - 2
ndep_proce - 7
nmun_proce - 34
npais_resi - 2
ndep_resi - 7
nmun_resi - 33
ndep_notif - 7
nmun_notif - 26
FechaHora - 328
RegIniFec - 0
vacio - 1

=== 2025 ===
cod_eve - 1
fec_not - 316
semana - 53
año - 1
cod_pre - 89
cod_sub - 15
pri_nom_ - 591
seg_nom_ - 262
pri_ape_ - 251
seg_ape_ - 216
tip_ide_ - 4
num_ide_ - 775
edad_ - 17
uni_med_ - 3
nacionali_ - 2
nombre_nacionalidad - 2
sexo_ - 2
iden_gener - 3
otra_ident - 0
orient_sex - 2
otra_orien - 0
cod_pais_o - 2
cod_dpto_o - 8
cod_mun_o - 30
area_ - 3
localidad_ - 36
cen_pobla_ - 39
vereda_ - 480
bar_ver_ - 133
dir_res_ - 765
lat_dir - 8
long_dir - 8
ocupacion_ - 4
tip_ss_ - 2
cod_ase_ - 2
per_etn_ - 3
nom_grupo_ - 7
estrato_ - 3
gp_discapa - 1
gp_desplaz - 2
gp_migrant - 2
gp_carcela - 1
gp_gestan - 1
sem_ges_ - 0
gp_indigen - 1
gp_pobicbf - 2
gp_mad_com - 1
gp_desmovi - 1
gp_psiquia - 1
gp_vic_vio - 1
gp_otros - 2
fuente_ - 4
cod_pais_r - 2
cod_dpto_r - 8
cod_mun_r - 31
fec_con_ - 310
ini_sin_ - 315
tip_cas_ - 1
pac_hos_ - 2
fec_hos_ - 234
con_fin_ - 1
fec_def_ - 1
ajuste_ - 5
telefono_ - 472
fecha_nto_ - 573
cer_def_ - 0
cbmte_ - 0
uni_modif - 99
nuni_modif - 89
fec_arc_xl - 4
nom_dil_f_ - 695
tel_dil_f_ - 457
fec_aju_ - 280
nit_upgd - 76
fm_fuerza - 0
fm_unidad - 0
fm_grado - 0
version - 19
pri_nom_ma - 607
seg_nom_ma - 191
pri_ape_ma - 287
seg_ape_ma - 195
tip_ide_ma - 9
num_ide_ma - 828
niv_educat - 5
menores - 10
peso_nac - 184
talla_nac - 20
edad_ges - 16
t_lechem - 34
e_complem - 18
crec_dllo - 2
esq_vac - 3
carne_vac - 2
peso_act - 161
talla_act - 206
per_braqui - 55
res_pr_ape - 3
imc - 124
zscore_pt - 704
clas_peso - 7
zscore_te - 778
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 10
estrato_datos_complementarios - 0
nom_eve - 1
nom_upgd - 89
npais_proce - 2
ndep_proce - 8
nmun_proce - 35
npais_resi - 2
ndep_resi - 8
nmun_resi - 35
ndep_notif - 7
nmun_notif - 28
FechaHora - 280
RegIniFec - 287
vacio - 1

### filtramos columnas con pocos valores únicos, que suelen ser targets en clasificación.

In [14]:
for year, df in datasets.items():
    print(f"\n=== {year} ===")
    for col in df.columns:
        unique_vals = df[col].nunique()
        if 2 <= unique_vals <= 10:
            print(col, "-", unique_vals)

=== 2020 ===
uni_med_ - 3
nacionali_ - 2
sexo_ - 2
iden_gener - 3
orient_sex - 2
cod_dpto_o - 6
area_ - 3
ocupacion_ - 3
tip_ss_ - 2
per_etn_ - 3
nom_grupo_ - 7
estrato_ - 3
gp_desplaz - 2
gp_migrant - 2
gp_indigen - 2
gp_pobicbf - 2
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_dpto_r - 5
pac_hos_ - 2
ajuste_ - 3
fec_aju_ - 7
niv_educat - 5
menores - 6
crec_dllo - 2
esq_vac - 3
carne_vac - 2
res_pr_ape - 3
clas_peso - 6
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 8
ndep_proce - 3
ndep_resi - 3
ndep_notif - 3

=== 2021 ===
uni_med_ - 3
nacionali_ - 2
sexo_ - 2
iden_gener - 3
orient_sex - 2
cod_dpto_o - 6
area_ - 3
ocupacion_ - 4
tip_ss_ - 2
per_etn_ - 3
nom_grupo_ - 8
estrato_ - 3
gp_desplaz - 2
gp_migrant - 2
gp_indigen - 2
gp_pobicbf - 2
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_dpto_r - 7
pac_hos_ - 2
ajuste_ - 4
fec_aju_ - 7
niv_educat - 5
menores - 7
crec_dllo - 2
esq_vac - 3
carne_vac - 2
res_pr_ape - 3
clas_peso - 7
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 9
ndep_proce - 3
ndep_resi - 3
ndep_notif - 3

=== 2022 ===
uni_med_ - 3
nacionali_ - 2
sexo_ - 2
iden_gener - 3
orient_sex - 3
cod_dpto_o - 7
area_ - 3
ocupacion_ - 5
tip_ss_ - 2
per_etn_ - 3
nom_grupo_ - 7
estrato_ - 3
gp_desplaz - 2
gp_migrant - 2
gp_indigen - 2
gp_pobicbf - 2
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_dpto_r - 6
pac_hos_ - 2
ajuste_ - 4
fec_aju_ - 7
niv_educat - 5
menores - 10
crec_dllo - 2
esq_vac - 3
carne_vac - 2
res_pr_ape - 3
clas_peso - 7
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 10
ndep_proce - 4
ndep_resi - 4
ndep_notif - 4

=== 2023 ===
tip_ide_ - 3
uni_med_ - 3
sexo_ - 2
cod_dpto_o - 3
area_ - 3
localidad_ - 8
cen_pobla_ - 2
bar_ver_ - 6
lat_dir - 2
long_dir - 2
ocupacion_ - 2
per_etn_ - 2
nom_grupo_ - 6
estrato_ - 2
gp_pobicbf - 2
gp_otros - 2
fuente_ - 4

cod_dpto_r - 4
pac_hos_ - 2
ajuste_ - 4
uni_modif - 4
nuni_modif - 4
fec_arc_xl - 8
version - 8
tip_ide_ma - 5
niv_educat - 4
menores - 7
edad_ges - 10
crec_dllo - 2
esq_vac - 3
carne_vac - 2
res_pr_ape - 3
clas_peso - 7
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 5
ndep_proce - 3
ndep_resi - 4
ndep_notif - 5

=== 2024 ===
tip_ide_ - 5
uni_med_ - 3
nacionali_ - 2
nombre_nacionalidad - 2
sexo_ - 2
iden_gener - 3
orient_sex - 3
otra_orien - 2
cod_pais_o - 2
cod_dpto_o - 7
area_ - 3
lat_dir - 2
long_dir - 2
ocupacion_ - 5
tip_ss_ - 2
cod_ase_ - 2
per_etn_ - 3
nom_grupo_ - 8
estrato_ - 3
gp_discapa - 2
gp_desplaz - 2
gp_migrant - 2
gp_indigen - 2
gp_pobicbf - 2
gp_vic_vio - 2
gp_otros - 2
fuente_ - 4
cod_pais_r - 2
cod_dpto_r - 7
pac_hos_ - 2
ajuste_ - 5
tip_ide_ma - 10
niv_educat - 5
menores - 10
crec_dllo - 2
esq_vac - 3
carne_vac - 2
res_pr_ape - 3
clas_peso - 7
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 9
npais_proce - 2
ndep_proce - 7
npais_resi - 2
ndep_resi - 7
ndep_notif - 7

=== 2025 ===
tip_ide_ - 4
uni_med_ - 3
nacionali_ - 2
nombre_nacionalidad - 2
sexo_ - 2
iden_gener - 3
orient_sex - 2
cod_pais_o - 2
cod_dpto_o - 8
area_ - 3
lat_dir - 8
long_dir - 8
ocupacion_ - 4
tip_ss_ - 2
cod_ase_ - 2
per_etn_ - 3
nom_grupo_ - 7
estrato_ - 3
gp_desplaz - 2
gp_migrant - 2
gp_pobicbf - 2
gp_otros - 2
fuente_ - 4
cod_pais_r - 2
cod_dpto_r - 8
pac_hos_ - 2
ajuste_ - 5
fec_arc_xl - 4
tip_ide_ma - 9
niv_educat - 5
menores - 10
crec_dllo - 2
esq_vac - 3
carne_vac - 2
res_pr_ape - 3
clas_peso - 7
clas_talla - 3
edema - 2
delgadez - 2
piel_rese - 2
hiperpigm - 2
cambios_cabello - 2
palidez - 2
ruta_atenc - 2
tipo_manej - 2
diag_medic - 10
npais_proce - 2
ndep_proce - 8
npais_resi - 2
ndep_resi - 8
ndep_notif - 7

In [15]:
for year, df in datasets.items():
    if "clas_peso" in df.columns:
        print(f"\n=== {year} ===")
        print(df["clas_peso"].value_counts(dropna=False))
    else:
        print(f"{year}: no tiene columna clas_peso")

=== 2020 ===
clas_peso
2.0    232
1.0     36
3.0     20
4.0     18
7.0      7
NaN      5
6.0      2
Name: count, dtype: int64

=== 2021 ===
clas_peso
2.0    414
1.0     60
4.0     44
3.0     27
NaN     12
5.0     11
7.0      7
6.0      5
Name: count, dtype: int64

=== 2022 ===
clas_peso
2.0    620
1.0     93
4.0     72
3.0     38
NaN     13
6.0      7
5.0      5
7.0      2
Name: count, dtype: int64

=== 2023 ===
clas_peso
2    66
1    14
3    11
4    10
5     3
7     2
6     1
Name: count, dtype: int64

=== 2024 ===
clas_peso
2.0    981
1.0    247
4.0     93
3.0     83
NaN     13
5.0     13
7.0      8
6.0      3
Name: count, dtype: int64

=== 2025 ===
clas_peso
2.0    731
1.0    179
4.0     79
3.0     49
5.0     11
7.0      3
6.0      3
NaN      2
Name: count, dtype: int64